//
//  fotaq_strings.h
//  scummvm
//
//  Created by Omer Gilad on 10/7/15.
//
//

#ifndef fotaq_strings_h
#define fotaq_strings_h


BEGIN_STRINGS


BEGIN_LOCALE(ENGLISH)


//
// Non-localized
//
DEF_STRING(english, "English")
DEF_STRING(english_sub, "English Subtitles")
DEF_STRING(german, "Deutsch")
DEF_STRING(german_sub, "Deutsch Untertitel")
DEF_STRING(spanish, "Español")
DEF_STRING(spanish_sub, "Subtítulos en Español")
DEF_STRING(portuguese, "Português")
DEF_STRING(portuguese_sub, "Legendas em Português")
DEF_STRING(french, "Français")
DEF_STRING(french_sub, "Sous-titres Français")
DEF_STRING(russian, "Pу́сский")
DEF_STRING(russian_sub, "Pусские Cубтитры")
DEF_STRING(italian, "Italiano")
DEF_STRING(italian_sub, "Sottotitoli Italiano")
DEF_STRING(czech, "Čeština")
DEF_STRING(czech_sub, "Ceské Titulky")
DEF_STRING(polish, "Polski")
DEF_STRING(polish_sub, "Polskie Napisy")
DEF_STRING(swedish, "Svenska")
DEF_STRING(swedish_sub, "Svenska undertexter")
DEF_STRING(hebrew, "עברית")
DEF_STRING(hebrew_sub, "כתוביות בעברית")

DEF_STRING(sfx_volume, "SFX")


DEF_STRING(quit, "EXIT")
DEF_STRING(no_sdcard, "Cannot access your external storage.")
DEF_STRING(restart_needed, "Your changes will apply after \'New Game\' OR \'Load\'.")
DEF_STRING(music_mode_no_music, "None")
DEF_STRING(music_mode_original, "AdLib")
DEF_STRING(music_mode_original_recording, "Original")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "General MIDI")
DEF_STRING(music_mode_enhanced, "New Recording")
DEF_STRING(voice_mode_voice_subtitles, "Voice And Subtitles")
DEF_STRING(voice_mode_voice_only, "Voice Only")
DEF_STRING(voice_mode_subtitles_only, "Subtitles Only")
DEF_STRING(subtitle_speed, "Subtitle Speed")
DEF_STRING(scaling_option_lq_shader, "Medium")
DEF_STRING(scaling_option_shader, "High")
DEF_STRING(scaling_option_shader_native_res, "Ultra")
DEF_STRING(scaling_option_software, "Low")
DEF_STRING(scaling_option_none, "Original")
DEF_STRING(aspect_ratio_desc, "Aspect Ratio:")
DEF_STRING(aspect_ratio_option_modern, "Modern")
DEF_STRING(aspect_ratio_option_original, "Original")
DEF_STRING(control_mode_touch, "Touch")
DEF_STRING(control_mode_touch_desc, "HOTSPOTS BASED CONTROLS")
DEF_STRING(control_mode_classic, "Classic")
DEF_STRING(control_mode_classic_desc, "DISPLAY CURSOR AND USE THE ACTIONS BUTTONS")
DEF_STRING(control_mode_touch_classic_bar, "TOUCH WITH ORIGINAL ACTIONS")
DEF_STRING(music_mode, "MUSIC")
DEF_STRING(voice_mode, "VOICE")
DEF_STRING(music_volume, "MUSIC")
DEF_STRING(speech_volume, "VOICE")
DEF_STRING(language, "LANGUAGE")
DEF_STRING(scaling_option, "GRAPHICS")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "Unable to create game files. Is your external storage accessible?")
DEF_STRING(unable_to_create_game_files_error_dialog, "The local game files are corrupt. Would you like to download the game files again?")
DEF_STRING(ok, "OK")
DEF_STRING(yes, "YES")
DEF_STRING(no, "NO")
DEF_STRING(text_validation_failed, "Expansion file validation failed. The file is corrupted and needs to be downloaded again.")
DEF_STRING(text_button_pause, "Pause")
DEF_STRING(text_button_resume, "Resume")
DEF_STRING(text_button_cancel, "CANCEL")
DEF_STRING(text_button_cancel_verify, "CANCEL")
DEF_STRING(failure_message_unknown, "Failed to start downloading game files.")
DEF_STRING(failure_message_cancelled, "The download was cancelled.")
DEF_STRING(failure_message_connection, "Could not connect to Google Play\'s servers.\nPlease try again later.")
DEF_STRING(failure_message_license, "According ot Google Play, this game client is unlicensed.")
DEF_STRING(failure_message_sdcard, "Storage is full, free up some space.")
DEF_STRING(preparing_game_files, "Preparing game files...")
DEF_STRING(cancel, "CANCEL")
DEF_STRING(exit_confirmation_message, "Exit the game now?\nUnsaved progress will be lost.")
DEF_STRING(expansion_downloader_upper_text, "Downloading game files")
DEF_STRING(expansion_downloader_upper_text_validating, "Validating game files")
DEF_STRING(choose_save_slot, "CHOOSE SAVE SLOT")
DEF_STRING(empty_slot, "Empty Slot")
DEF_STRING(choose_load_slot, "CHOOSE SLOT TO LOAD")
DEF_STRING(enter_save_name, "Enter save name:")
DEF_STRING(save_success, "Game saved successfully")
DEF_STRING(save_failure, "Cannot save the game at this time")
DEF_STRING(load_success, "Loaded game successfully")
DEF_STRING(load_failure, "Cannot load at this time")
DEF_STRING(load_failure_no_saves, "No save games are available. Please save the game first.")
DEF_STRING(save_game_reminder, "%s is paused - it is recommended that you save your game from time to time.")
DEF_STRING(files_fraction, "%1$s / %2$s files")
DEF_STRING(save_progress_dialog, "Saving, please wait...")
DEF_STRING(load_progress_dialog, "Loading, please wait...")
DEF_STRING(no_saved_games, "There are no saved games")
DEF_STRING(continue_, "CONTINUE")
DEF_STRING(save_game, "SAVE")
DEF_STRING(load_game, "LOAD")
DEF_STRING(new_game, "NEW GAME")
DEF_STRING(settings, "SETTINGS")
DEF_STRING(tutorial, "TUTORIAL")
DEF_STRING(game_tutorial, "Game Tutorial")
DEF_STRING(exit_button, "QUIT")
DEF_STRING(controls, "CONTROLS")
DEF_STRING(about, "ABOUT")
DEF_STRING(back, "BACK")
DEF_STRING(menu_subtitle, "25TH ANNIVERSARY EDITION")
DEF_STRING(shader_test_message, "Testing graphics performance (first time only)")
DEF_STRING(rate_message, "We hope that you enjoy playing %s. Please rate it!")
DEF_STRING(rate, "Yes, rate now!")
DEF_STRING(rate_later, "Remind me later")
DEF_STRING(rate_cancel, "No, thanks")
DEF_STRING(tutorial_prompt, "Would you like to watch the tutorial video?")
DEF_STRING(graphic_setting_message, "For smooth gameplay, do not increase the default graphic settings - they are based on your device\'s graphic performance (GPU).")
DEF_STRING(mt32_warning_message, "Please note that this feature is not supported on all devices. If you experience \"cracking\" in the music or low performance, please try to reboot your device and to choose another option from this list.")
DEF_STRING(prepare_game_files_no_space_message, "There is no free space on your device.\nPlease free up %s and then start again.")
DEF_STRING(storage_unavailable, "Your device\'s storage is unavailable - is it connected as a USB drive?")
DEF_STRING(new_game_confirmation, "Are you sure you want to start a new game?\nYour unsaved progress will be lost.")
DEF_STRING(rate_us, "RATE US")
DEF_STRING(store_page, "Store Page")
DEF_STRING(share_chooser, "Share with...")
DEF_STRING(share_message, "Check out this cool new game I just bought - a timeless classic!")
DEF_STRING(open_house_prompt, "This will start a new game in \'Open House\' mode, which allows you to replay all the puzzles in the game for your leisure. Continue?")
DEF_STRING(achievement_popup_title, "You got an achievement!")
DEF_STRING(enable_achievement_popup_checkbox, "Show achievement popups")
DEF_STRING(facebook_share_achievement_btn, "Share with Facebook")
DEF_STRING(facebook_login_dialog_title, "Log into Facebook in order to share your game achievements!")
DEF_STRING(facebook_share_achievement_dialog_title, "Share the new achievement on your wall...")
DEF_STRING(facebook_share_achievement_input_hint, "Your message here")
DEF_STRING(facebook_share_achievement_success_toast, "The achievement was shared successfully")
DEF_STRING(facebook_share_achievement_failure_toast, "There was an error while sharing the achievement")
DEF_STRING(skip_english_puzzle_popup, "The following puzzle is English-based, and does not fully support your language.\nWould you like to skip it?")
DEF_STRING(microscope_puzzle_popup, "TIP: select the game piece, and then select the destination to make it move.")
DEF_STRING(like_view_error, "There was an error while using the Like button")
DEF_STRING(error_opening_extra_file, "Could not open the file %s. Make sure you have an appropriate app installed.")
DEF_STRING(error_opening_epub_file, "You need to install an app that can open Books (.epub files)")
DEF_STRING(achievements, "Achievements")
DEF_STRING(extras, "Extras")
DEF_STRING(bishops_puzzle_popup, "Touch a bishop in order to move it. Sometimes there are multiple destinations, and sometimes a bishop cannot move at all.")
DEF_STRING(load_change_language_popup, "This save was created with a different language of the game and can\'t be used.\nWould you like to switch to that language before loading?")
DEF_STRING(no_amazon_appstore, "The Amazon Appstore is not installed on this device")

// TODO: localize
DEF_STRING(control_mode_enhanced_desktop, "Enhanced")
DEF_STRING(control_mode_enhanced_desktop_classic_bar, "Enhanced with original actions")

DEF_STRING(music_mode_original_general_midi, "General MIDI")

END_LOCALE


BEGIN_LOCALE(GERMAN)

DEF_STRING(quit, "BEENDEN")
DEF_STRING(no_sdcard, "KANN AUF EXTERNEN SPEICHER NICHT ZUGREIFEN.")
DEF_STRING(restart_needed, "ÄNDERUNGEN WERDEN WIRKSAM NACH DEM START EINES NEUEN SPIELS ODER DURCH LADEN EINES SPIELSTANDS.")
DEF_STRING(music_mode_no_music, "KEINER")
DEF_STRING(music_mode_original, "AdLib")
DEF_STRING(music_mode_original_recording, "Original")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "General MIDI")
DEF_STRING(music_mode_enhanced, "NEUE AUFNAHME")
DEF_STRING(voice_mode_voice_subtitles, "SPRACHAUSGABE UND UNTERTITEL")
DEF_STRING(voice_mode_voice_only, "NUR SPRACHAUSGABE")
DEF_STRING(voice_mode_subtitles_only, "NUR UNTERTITEL")
DEF_STRING(subtitle_speed, "Untertitel-Geschwindigkeit")
DEF_STRING(scaling_option_lq_shader, "MITTEL")
DEF_STRING(scaling_option_shader, "HOCH")
DEF_STRING(scaling_option_shader_native_res, "ULTRA")
DEF_STRING(scaling_option_software, "NIEDRIG")
DEF_STRING(scaling_option_none, "ORIGINAL")
DEF_STRING(aspect_ratio_desc, "Seitenverhältnis:")
DEF_STRING(aspect_ratio_option_modern, "MODERN")
DEF_STRING(aspect_ratio_option_original, "ORIGINAL")
DEF_STRING(control_mode_touch, "BERÜHRUNG")
DEF_STRING(control_mode_touch_desc, "AUF BRENNPUNKTEN BASIERENDE STEUERUNG")
DEF_STRING(control_mode_touch_classic_bar, "BEDIENOBERFLÄCHE MIT ORIGINAL-SYMBOLEN")
DEF_STRING(control_mode_classic, "KLASSISCH")
DEF_STRING(control_mode_classic_desc, "CURSOR ANZEIGEN UND AKTIONSTASTEN NUTZEN")
DEF_STRING(music_mode, "MUSIK")
DEF_STRING(voice_mode, "SPRACHAUSGABE")
DEF_STRING(music_volume, "MUSIK")
DEF_STRING(speech_volume, "SPRACHAUSGABE")
DEF_STRING(language, "SPRACHE")
DEF_STRING(scaling_option, "GRAFIK")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "Kann Spieldateien nicht erstellen. Ist externer Speicherplatz verfügbar?")
DEF_STRING(unable_to_create_game_files_error_dialog, "Die lokalen Spieldateien sind beschädigt. Sollen die Spieldateien erneut heruntergeladen werden?")
DEF_STRING(ok, "OK")
DEF_STRING(yes, "JA")
DEF_STRING(no, "NEIN")
DEF_STRING(text_validation_failed, "Gültigkeitsprüfung der Erweiterungsdatei gescheitert. Die Datei ist beschädigt und muss erneut heruntergeladen werden.")
DEF_STRING(text_button_pause, "PAUSE")
DEF_STRING(text_button_resume, "FORTSETZEN")
DEF_STRING(text_button_cancel, "ABBRECHEN")
DEF_STRING(text_button_cancel_verify, "ABBRECHEN")
DEF_STRING(failure_message_unknown, "HERUNTERLADEN DER SPIELDATEIEN KONNTE NICHT GESTARTET WERDEN.")
DEF_STRING(failure_message_cancelled, "DER DOWNLOAD WURDE ABGEBROCHEN.")
DEF_STRING(failure_message_connection, "KONNTE NICHT MIT DEN SERVERN VON GOOGLE PLAY VERBINDEN. BITTE SPÄTER ERNEUT VERSUCHEN.")
DEF_STRING(failure_message_license, "GEMÄSS GOOGLE PLAY IST DIESE KOPIE DES SPIELES NICHT LIZENSIERT.")
DEF_STRING(failure_message_sdcard, "SPEICHER IST VOLL, BITTE SPEICHERPLATZ SCHAFFEN.")
DEF_STRING(preparing_game_files, "SPIELDATEIEN WERDEN VORBEREITET...")
DEF_STRING(cancel, "ABBRECHEN")
DEF_STRING(exit_confirmation_message, "Beenden Sie das Spiel jetzt? NICHT GESPEICHERTER FORTSCHRITT GEHT VERLOREN.")
DEF_STRING(expansion_downloader_upper_text, "SPIELDATEIEN WERDEN HERUNTERGELADEN")
DEF_STRING(expansion_downloader_upper_text_validating, "SPIELEDATEIEN WERDEN AUF GÜLTIGKEIT GEPRÜFT")
DEF_STRING(choose_save_slot, "SPEICHERN")
DEF_STRING(empty_slot, "leer")
DEF_STRING(choose_load_slot, "LADEN")
DEF_STRING(enter_save_name, "NAMEN FÜR DEN SPIELSTAND EINGEBEN:")
DEF_STRING(save_success, "Spiel erfolgreich gespeichert.")
DEF_STRING(save_failure, "Kann Spiel zurzeit nicht speichern.")
DEF_STRING(load_success, "Spiel erfolgreich geladen.")
DEF_STRING(load_failure, "Kann Spiel zurzeit nicht laden.")
DEF_STRING(save_game_reminder, "%s ist pausiert – es wird empfohlen, dass Spiel von Zeit zu Zeit zu speichern.")
DEF_STRING(files_fraction, "%1$s / %2$s Dateien")
DEF_STRING(save_progress_dialog, "SPEICHERT GERADE, BITTE WARTEN ...")
DEF_STRING(load_progress_dialog, "LÄDT GERADE, BITTE WARTEN ...")
DEF_STRING(no_saved_games, "Es gibt keine gespeicherten Spielstände.")
DEF_STRING(continue_, "FORTFAHREN")
DEF_STRING(save_game, "SPEICHERN")
DEF_STRING(load_game, "LADEN")
DEF_STRING(new_game, "NEUES SPIEL")
DEF_STRING(settings, "EINSTELLUNGEN")
DEF_STRING(tutorial, "ANLEITUNG")
DEF_STRING(game_tutorial, "Spiel Tutorial")
DEF_STRING(exit_button, "BEENDEN")
DEF_STRING(controls, "SPIELSTEUERUNG")
DEF_STRING(about, "ÜBER")
DEF_STRING(back, "ZURÜCK")
DEF_STRING(menu_subtitle, "25TH ANNIVERSARY EDITION")
DEF_STRING(shader_test_message, "Grafik-Leistung wird getestet (nur beim ersten Mal)")
DEF_STRING(rate_message, "Wir hoffen, dass Sie viel Freude dabei haben, %s zu spielen. Bitte bewerten Sie das Spiel!")
DEF_STRING(rate, "JA, JETZT BEWERTEN")
DEF_STRING(rate_later, "SPÄTER DARAN ERINNERN")
DEF_STRING(rate_cancel, "NEIN, DANKE")
DEF_STRING(tutorial_prompt, "MÖCHTEST DU DIE VIDEO-ANLEITUNG SEHEN ?")
DEF_STRING(graphic_setting_message, "Um ruckelfrei spielen zu können, erhöhe nicht die standardmäßigen Grafikeinstellungen - sie basieren auf der Grafikleistung (GPU) des Geräts.")
DEF_STRING(mt32_warning_message, "Bitte beachte, dass diese Funktion nicht auf allen Geräten unterstützt wird. Wenn die Musik „stottert“ oder zu langsam abgespielt wird, fahre bitte das Gerät neu hoch und wähle eine andere Option aus dieser Liste aus.")
DEF_STRING(prepare_game_files_no_space_message, "AUF DEM GERÄT IST KEIN FREIER SPEICHER VERFÜGBAR. BITTE MACHE %s FREI UND STARTE DANN ERNEUT.")
DEF_STRING(storage_unavailable, "DER GERÄTESPEICHER IST NICHT VERFÜBAR - IST ER ALS USB-GERÄT ANGESCHLOSSEN?")
DEF_STRING(new_game_confirmation, "MÖCHTEST DU WIRKLICH EIN NEUES SPIEL STARTEN? DEIN NICHT GESPEICHERTER SPIELSTAND GEHT VERLOREN.")
DEF_STRING(rate_us, "Bewerten Sie uns")
DEF_STRING(store_page, "Seite speichern")
DEF_STRING(share_chooser, "Share with...")
DEF_STRING(share_message, "Check out this cool new game I just bought - a timeless classic!")
DEF_STRING(open_house_prompt, "This will start a new game in \'Open House\' mode, which allows you to replay all the puzzles in the game for your leisure. Continue?")
DEF_STRING(achievement_popup_title, "You got an achievement!")
DEF_STRING(enable_achievement_popup_checkbox, "Show achievement popups")
DEF_STRING(facebook_share_achievement_btn, "Share with Facebook")
DEF_STRING(facebook_login_dialog_title, "Log into Facebook in order to share your game achievements!")
DEF_STRING(facebook_share_achievement_dialog_title, "Share the new achievement on your wall...")
DEF_STRING(facebook_share_achievement_input_hint, "Your message here")
DEF_STRING(facebook_share_achievement_success_toast, "The achievement was shared successfully")
DEF_STRING(facebook_share_achievement_failure_toast, "There was an error while sharing the achievement")
DEF_STRING(skip_english_puzzle_popup, "The following puzzle is English-based, and does not fully support your language.\nWould you like to skip it?")
DEF_STRING(microscope_puzzle_popup, "TIP: select the game piece, and then select the destination to make it move.")
DEF_STRING(like_view_error, "There was an error while using the Like button")
DEF_STRING(error_opening_extra_file, "Could not open the file %s. Make sure you have an appropriate app installed.")
DEF_STRING(error_opening_epub_file, "You need to install an app that can open Books (.epub files)")
DEF_STRING(achievements, "Achievements")
DEF_STRING(extras, "Extras")
DEF_STRING(bishops_puzzle_popup, "Touch a bishop in order to move it. Sometimes there are multiple destinations, and sometimes a bishop cannot move at all.")
DEF_STRING(load_change_language_popup, "Der Spielstand wurde in einer anderen Sprache des Spiels gespeichert und kann nicht verwendet werden.\nVor dem Laden zu dieser Sprache wechseln?")
DEF_STRING(no_amazon_appstore, "The Amazon Appstore is not installed on this device")


END_LOCALE



BEGIN_LOCALE(FRENCH)

DEF_STRING(quit, "QUITTER")
DEF_STRING(no_sdcard, "Impossible d\'acceder a un stockage externe.")
DEF_STRING(restart_needed, "Vos changements seront appliques apres \'Nouvelle Partie\' ou \'Charger\'.")
DEF_STRING(music_mode_no_music, "Aucune")
DEF_STRING(music_mode_original, "AdLib")
DEF_STRING(music_mode_original_recording, "Originelle")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "General MIDI")
DEF_STRING(music_mode_enhanced, "Nouvel Enregistrement")
DEF_STRING(voice_mode_voice_subtitles, "Voix et sous-titres")
DEF_STRING(voice_mode_voice_only, "Voix uniquement")
DEF_STRING(voice_mode_subtitles_only, "Sous-titres uniquement")
DEF_STRING(subtitle_speed, "Vitesse des sous-titres")
DEF_STRING(scaling_option_lq_shader, "Moyen")
DEF_STRING(scaling_option_shader, "Eleve")
DEF_STRING(scaling_option_shader_native_res, "Ultra")
DEF_STRING(scaling_option_software, "Bas")
DEF_STRING(scaling_option_none, "Originel")
DEF_STRING(aspect_ratio_desc, "Ratio d'aspect:")
DEF_STRING(aspect_ratio_option_modern, "Moderne")
DEF_STRING(aspect_ratio_option_original, "Originel")
DEF_STRING(control_mode_touch, "Tactile")
DEF_STRING(control_mode_touch_desc, "COMMANDES BASEES SUR LES ENDROITS CLES")
DEF_STRING(control_mode_touch_classic_bar, "TACTILE AVEC ACTIONS D\'ORIGINES")
DEF_STRING(control_mode_classic, "Classic")
DEF_STRING(control_mode_classic_desc, "AFFICHEZ LE CURSEUR ET UTILISEZ LES TOUCHES D\'ACTION")
DEF_STRING(music_mode, "Musique")
DEF_STRING(voice_mode, "Voix")
DEF_STRING(music_volume, "Musique")
DEF_STRING(speech_volume, "Voix")
DEF_STRING(language, "Langage")
DEF_STRING(scaling_option, "Graphiques")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "Impossible de creer les fichiers du jeu. Un stockage externe est-il disponible ?")
DEF_STRING(unable_to_create_game_files_error_dialog, "Les fichiers du jeu sont corrompus. Voulez-vous les telecharger de nouveau ?")
DEF_STRING(ok, "OK")
DEF_STRING(yes, "OUI")
DEF_STRING(no, "NON")
DEF_STRING(text_validation_failed, "La validation du fichier d\'extension a echouee. Le fichier est corrompu et doit etre telecharge de nouveau.")
DEF_STRING(text_button_pause, "Pause")
DEF_STRING(text_button_resume, "Reprendre")
DEF_STRING(text_button_cancel, "ANNULER")
DEF_STRING(text_button_cancel_verify, "ANNULER")
DEF_STRING(failure_message_unknown, "Le telechargement des fichiers du jeu a echoue.")
DEF_STRING(failure_message_cancelled, "Le telechargement a ete annule.")
DEF_STRING(failure_message_connection, "Impossible de se connecter aux serveur de Google Play.\nEssayez de nouveau plus tard.")
DEF_STRING(failure_message_license, "Selon Google Play, ce client de jeu est sans licence.")
DEF_STRING(failure_message_sdcard, "Le disque de stockage est plein, liberez de l\'espace.")
DEF_STRING(preparing_game_files, "Preparation des fichiers du jeu…")
DEF_STRING(cancel, "ANNULER")
DEF_STRING(exit_confirmation_message, "Quittez le jeu maintenant ?\nLes progres non sauvegardes seront perdus.")
DEF_STRING(expansion_downloader_upper_text, "Telechargement des fichiers du jeu")
DEF_STRING(expansion_downloader_upper_text_validating, "Validation des fichiers du jeu")
DEF_STRING(choose_save_slot, "Sauvegarder")
DEF_STRING(empty_slot, "emplacement vide")
DEF_STRING(choose_load_slot, "Charger")
DEF_STRING(enter_save_name, "Nom de la sauvegarde:")
DEF_STRING(save_success, "Succes de la sauvegarde")
DEF_STRING(save_failure, "Impossible de sauver la partie pour l\'instant")
DEF_STRING(load_success, "Succes du chargement")
DEF_STRING(load_failure, "Impossible de charger la partie pour l\'instant")
DEF_STRING(save_game_reminder, "%s est en pause - il est recommande de sauvegarder la partie de temps en temps.")
DEF_STRING(files_fraction, "%1$s / %2$s fichiers")
DEF_STRING(save_progress_dialog, "Sauvegarde en cours…")
DEF_STRING(load_progress_dialog, "Chargement en cours…")
DEF_STRING(no_saved_games, "Il n\'y a pas de partie sauvegardee")
DEF_STRING(continue_, "Continuer")
DEF_STRING(save_game, "Sauvegarder")
DEF_STRING(load_game, "Charger")
DEF_STRING(new_game, "Nouvelle Partie")
DEF_STRING(settings, "Options")
DEF_STRING(tutorial, "Tutoriel")
DEF_STRING(game_tutorial, "Tutoriel du jeu")
DEF_STRING(exit_button, "ADIEU")
DEF_STRING(controls, "Commandes")
DEF_STRING(about, "a propos")
DEF_STRING(back, "Retour")
DEF_STRING(menu_subtitle, "EDITION DU 25IEME ANNIVERSAIRE")
DEF_STRING(shader_test_message, "Test des performances graphiques (premier lancement uniquement)")
DEF_STRING(rate_message, "Nous espérons que vous aimez jouer a %s. Noter le s\'il vous plait !")
DEF_STRING(rate, "Oui, mettre une note maintenant !")
DEF_STRING(rate_later, "Me le rappeler plus tard")
DEF_STRING(rate_cancel, "Non, merci")
DEF_STRING(tutorial_prompt, "Voulez-vous regarder le tutoriel video ?")
DEF_STRING(graphic_setting_message, "Pour un jeu sans saccades, gardez les parametres graphiques par defaut – ils prennent en compte les performances graphiques (GPU) de votre appareil.")
DEF_STRING(mt32_warning_message, "Veuillez notez que cette fonctionalite n\'est supportee sur tous les appareils. Si vous rencontrez des \"craquement\" dans la musique ou des faibles performances, essayez de redemarrer votre appareil et de choisir une option differente dans cette liste.")
DEF_STRING(prepare_game_files_no_space_message, "Il n\'y a pas d\'espace disponible sur votre appareil.\nVeuillez liberer %s puis reessayer.")
DEF_STRING(storage_unavailable, "Le peripherique de stockage de votre appareil n\'est pas disponible – est-il connecte comme disque USB ?")
DEF_STRING(new_game_confirmation, "Etes vous sur de vouloir commencer une nouvelle partie ?\nVos progres non sauvegardes seront perdus.")
DEF_STRING(rate_us, "Nous Evaluer")
DEF_STRING(store_page, "Store Page")
DEF_STRING(share_chooser, "Partager…")
DEF_STRING(share_message, "Decouvrez ce nouveau jeu cool que je viens d\'acheter – un classique qui ne vieillit pas !")
DEF_STRING(open_house_prompt, "Cela commencera une nouvelle partie en mode \'Maison Ouverte\', qui permet de rejouer tous les puzzles du jeu a votre guise. Continuer ?")
DEF_STRING(achievement_popup_title, "Vous avez un Succes !")
DEF_STRING(enable_achievement_popup_checkbox, "Afficher les Succes")
DEF_STRING(facebook_share_achievement_btn, "Partager sur Facebook")
DEF_STRING(facebook_login_dialog_title, "Connectez-vous a Facebook pour partager vos Succes !")
DEF_STRING(facebook_share_achievement_dialog_title, "Postez les nouveaux Succes sur votre mur…")
DEF_STRING(facebook_share_achievement_input_hint, "Votre message ici")
DEF_STRING(facebook_share_achievement_success_toast, "Le Succes a ete partage avec succes")
DEF_STRING(facebook_share_achievement_failure_toast, "Une erreur est intervenue lors du partage de votre Succes")
DEF_STRING(skip_english_puzzle_popup, "Le puzzle suivant est base sur l'anglais, et ne supporte pas totalement votre langue.\nVoulez-vous le sauter ?")
DEF_STRING(microscope_puzzle_popup, "Astuce : Selectionez une piece du jeu, et ensuite selectionez une destination pour la deplacer.")
DEF_STRING(like_view_error, "Une erreur est survenue lors de l\'utilisation du bouton \'J\'aime\'.")
DEF_STRING(error_opening_extra_file, "Erreur lors de l\'ouverture du fichier %s. Vérifier que vous avez installe une application appropriee pour le lire.")
DEF_STRING(error_opening_epub_file, "Vous avez besoin d\'installer une application qui peut ouvrir les livres electroniques (fichiers .epub).")
DEF_STRING(achievements, "Succes")
DEF_STRING(extras, "Supplements")
DEF_STRING(bishops_puzzle_popup, "Selectionnez le fou pour le deplacer. Parfois plusieurs directions sont possibles, parfois aucune.")
DEF_STRING(load_change_language_popup, "Cette sauvegarde a ete creee dans une langue du jeu differente et ne peut pas etre utilisee.\nVoulez-vous selectionner cette langue avant le chargement ?")
DEF_STRING(no_amazon_appstore, "The Amazon Appstore is not installed on this device")

END_LOCALE



BEGIN_LOCALE(SPANISH)

DEF_STRING(no_sdcard, "No se puede acceder al almacenamiento externo.")
DEF_STRING(prepare_game_files_no_space_message, "No hay espacio libre en su dispositivo.\nPor favor libere %s y después empiece de nuevo.")
DEF_STRING(storage_unavailable, "El almacenamiento de su dispositivo no está disponible - ¿está conectado como un disco USB?")
DEF_STRING(restart_needed, "Sus cambios se aplicarán después de \'Empezar nuevo\' O \'Cargar\'.")
DEF_STRING(music_mode_no_music, "Ninguno")
DEF_STRING(music_mode_original_recording, "Original")
DEF_STRING(music_mode_enhanced, "Nueva grabación")
DEF_STRING(music_mode_original, "AdLib")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "General MIDI")
DEF_STRING(voice_mode_voice_subtitles, "Voz y subtítulos")
DEF_STRING(voice_mode_voice_only, "Voz solamente")
DEF_STRING(voice_mode_subtitles_only, "Subtítulos solamente")
DEF_STRING(subtitle_speed, "Velocidad de subtítulos")
DEF_STRING(scaling_option, "GRÁFICOS")
DEF_STRING(scaling_option_none, "Original")
DEF_STRING(scaling_option_software, "Bajo")
DEF_STRING(scaling_option_lq_shader, "Medio")
DEF_STRING(scaling_option_shader, "Alto")
DEF_STRING(scaling_option_shader_native_res, "Ultra")
DEF_STRING(aspect_ratio_desc, "Relación de aspecto:")
DEF_STRING(aspect_ratio_option_modern, "Moderno")
DEF_STRING(aspect_ratio_option_original, "Original")
DEF_STRING(control_mode_classic, "Clásico")
DEF_STRING(control_mode_classic_desc, "MOSTRAR EL CURSOR Y UTILIZAR LOS BOTONES DE ACCIONES")
DEF_STRING(control_mode_touch, "Táctil")
DEF_STRING(control_mode_touch_desc, "CONTROLES BASADOS EN PUNTO DE ACCESO")
DEF_STRING(control_mode_touch_classic_bar, "TÁCTIL CON ACCIONES ORIGINALES")
DEF_STRING(music_mode, "MÚSICA")
DEF_STRING(voice_mode, "VOZ")
DEF_STRING(music_volume, "MÚSICA")
DEF_STRING(speech_volume, "VOZ")
DEF_STRING(language, "IDIOMA")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "No se han podido crear los archivos del juego. ¿Su almacenamiento externo se encuentra accesible?")
DEF_STRING(unable_to_create_game_files_error_dialog, "Los archivos locales del juego están corruptos. ¿Le gustaría descargar los archivos del juego de nuevo?")
DEF_STRING(ok, "OK")
DEF_STRING(yes, "SÍ")
DEF_STRING(no, "NO")
DEF_STRING(text_validation_failed, "La validación del archivo de expansión ha fallado. El archivo está corrupto y necesita ser descargado de nuevo.")
DEF_STRING(text_button_pause, "Pausa")
DEF_STRING(text_button_resume, "Continuar")
DEF_STRING(text_button_cancel, "CANCELAR")
DEF_STRING(text_button_cancel_verify, "CANCELAR")
DEF_STRING(cancel, "CANCELAR")
DEF_STRING(preparing_game_files, "Preparando archivos del juego...")
DEF_STRING(failure_message_unknown, "Fallo al comenzar a descargar los archivos del juego.")
DEF_STRING(failure_message_cancelled, "La descarga ha sido cancelada.")
DEF_STRING(failure_message_connection, "No se ha podido conectar a los servidores de Google Play.\nPor favor pruebe de nuevo más tarde.")
DEF_STRING(failure_message_license, "De acuerdo con Google Play, este cliente del juego no tiene licencia.")
DEF_STRING(failure_message_sdcard, "El almacenamiento está lleno, libere algo de espacio.")
DEF_STRING(exit_confirmation_message, "¿Salir ahora?\nEl progreso no guardado se perderá.")
DEF_STRING(expansion_downloader_upper_text, "Descargando los archivos del juego")
DEF_STRING(expansion_downloader_upper_text_validating, "Validando los archivos del juego")
DEF_STRING(choose_save_slot, "Escoger espacio para guardar")
DEF_STRING(empty_slot, "ranura vacia")
DEF_STRING(choose_load_slot, "Escoger espacio para cargar")
DEF_STRING(enter_save_name, "Introducir nombre de guardado:")
DEF_STRING(save_success, "Juego guardado con éxito")
DEF_STRING(save_failure, "No se ha podido guardar el juego en este momento")
DEF_STRING(load_success, "Juego cargado con éxito")
DEF_STRING(load_failure, "No se ha podido cargar en este momento")
DEF_STRING(save_game_reminder, "%s está pausado - se recomienda que guarde el juego de vez en cuando.")
DEF_STRING(files_fraction, "%1$s / %2$s archivos")
DEF_STRING(save_progress_dialog, "Guardando, por favor espere...")
DEF_STRING(load_progress_dialog, "Cargando, por favor espere...")
DEF_STRING(no_saved_games, "No hay juegos guardados")
DEF_STRING(continue_, "CONTINUAR")
DEF_STRING(save_game, "GUARDAR")
DEF_STRING(load_game, "CARGAR")
DEF_STRING(new_game, "NUEVO JUEGO")
DEF_STRING(settings, "AJUSTES")
DEF_STRING(tutorial, "TUTORIAL")
DEF_STRING(game_tutorial, "Tutorial del juego")
DEF_STRING(exit_button, "QUITAR")
DEF_STRING(quit, "SALIR")
DEF_STRING(controls, "CONTROLES")
DEF_STRING(about, "SOBRE")
DEF_STRING(back, "VOLVER")
DEF_STRING(extras, "EXTRAS")
DEF_STRING(menu_subtitle, "EDICIÓN 25 ANIVERSARIO")
DEF_STRING(shader_test_message, "Probando el rendimiento de los gráficos(primera vez solamente)")
DEF_STRING(rate_message, "Esperamos que haya disfrutado jugando a %s. Por favor puntúelo")
DEF_STRING(rate, "Sí, puntuar ahora")
DEF_STRING(rate_later, "Recordarme más tarde")
DEF_STRING(rate_cancel, "No, gracias")
DEF_STRING(tutorial_prompt, "¿Le gustaría ver el vídeo tutorial?")
DEF_STRING(graphic_setting_message, "Para un modo de juego suave, no incremente los ajustes gráficos por defecto - están basados en el rendimiento gráfico de su dispositivo(GPU).")
DEF_STRING(mt32_warning_message, "Por favor tenga en cuenta que esta característica no está soportada en todos los dispositivos. Si experimenta una \"rotura\" en la música o un bajo rendimiento, por favor intente reiniciar su dispositivo e escoger otra opción de esta lista.")
DEF_STRING(new_game_confirmation, "¿Está seguro de que desea comenzar un juego nuevo?\nSus progresos no guardados se perderán.")
DEF_STRING(rate_us, "PUNTÚENOS")
DEF_STRING(store_page, "Página de la tienda")
DEF_STRING(share_chooser, "Compartir con...")
DEF_STRING(share_message, "Eche un vistazo a este genial juego nuevo que acabo de comprar - un clásico atemporal %s")
DEF_STRING(open_house_prompt, "Esto comenzará un nuevo juego en el modo \'Casa Abierta\', el cual le permite reproducir todos los rompecabezas del juego para su entretenimiento. ¿Continuar?")
DEF_STRING(achievements, "Logros")
DEF_STRING(achievement_popup_title, "Ha obtenido un ligro")
DEF_STRING(enable_achievement_popup_checkbox, "Mostrar ventanas emergentes de logros")
DEF_STRING(facebook_share_achievement_btn, "Compartir con Facebook")
DEF_STRING(facebook_login_dialog_title, "Inicie sesión enFacebook con el fin de compartir sus logros del juego")
DEF_STRING(facebook_share_achievement_dialog_title, "Comparta el nuevo logro en su muro...")
DEF_STRING(facebook_share_achievement_input_hint, "Su mensaje aquí")
DEF_STRING(facebook_share_achievement_success_toast, "El logro ha sido compartido con éxito")
DEF_STRING(facebook_share_achievement_failure_toast, "Ha habido un error mientras se compartía el logro")
DEF_STRING(skip_english_puzzle_popup, "El siguiente rompecabezas está basado en inglés, y no soporta completamente su idioma.\n¿Le gustaría saltarlo?")
DEF_STRING(microscope_puzzle_popup, "CONSEJO: seleccione la pieza del juego, y después seleccione el destino para hacer el movimiento.")
DEF_STRING(like_view_error, "Ha ocurrido un error mientras se utilizaba el botón Me gusta")
DEF_STRING(error_opening_extra_file, "No se ha podido abrir el archivo %s. Asegúrese de que tiene una aplicación apropiada instalada.")
DEF_STRING(error_opening_epub_file, "Necesita instalar una aplicación que pueda abrir libros (archivos .epub)")
DEF_STRING(load_change_language_popup, "Este guardado ha sido creado con un idioma diferente al del juego y no puede utilizarse.\n¿Le gustaría cambiar a ese idioma antes de cargar?")
DEF_STRING(bishops_puzzle_popup, "Toque un alfil con el fin de moverlo. A veces hay múltiples destinos, y a veces el alfil no puede moverse. ")
DEF_STRING(no_amazon_appstore, "La tienda de aplicaciones de Amazon no está instalada en este dispositivo")

END_LOCALE


BEGIN_LOCALE(PORTUGESE)

DEF_STRING(quit, "SAIR")
DEF_STRING(restart_needed, "Suas mudanças serão aplicadas após \'Novo jogo\' OU \'Carregar\'.")
DEF_STRING(music_mode_no_music, "Desligado")
DEF_STRING(music_mode_original, "AdLib")
DEF_STRING(music_mode_original_recording, "Original")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "Geral MIDI (EAS)")
DEF_STRING(music_mode_enhanced, "Nova gravação")
DEF_STRING(voice_mode_voice_subtitles, "Voz e Legendas")
DEF_STRING(voice_mode_voice_only, "Apenas Voz")
DEF_STRING(voice_mode_subtitles_only, "Apenas Legendas")
DEF_STRING(subtitle_speed, "Velocidade das Legendas")
DEF_STRING(scaling_option_lq_shader, "Média")
DEF_STRING(scaling_option_shader, "Alta")
DEF_STRING(scaling_option_shader_native_res, "Ultra")
DEF_STRING(scaling_option_software, "Baixa")
DEF_STRING(scaling_option_none, "Original")
DEF_STRING(aspect_ratio_desc, "Proporção da tela:")
DEF_STRING(aspect_ratio_option_modern, "Moderno")
DEF_STRING(aspect_ratio_option_original, "Original")
DEF_STRING(control_mode_touch, "Toque")
DEF_STRING(control_mode_touch_desc, "CONTROLES BASEADOS EM PONTOS ESPECÍFICOS")
DEF_STRING(control_mode_classic, "Clássico")
DEF_STRING(control_mode_classic_desc, "MOSTRAR CURSOR E USAR BOTÕES DE AÇÃO")
DEF_STRING(control_mode_touch_classic_bar, "TOQUE COM AÇÕES ORIGINAIS")
DEF_STRING(control_mode_enhanced_desktop, "Melhorado")
DEF_STRING(control_mode_enhanced_desktop_classic_bar, "Melhorado com ações originais")
DEF_STRING(music_mode, "MÚSICA")
DEF_STRING(voice_mode, "VOZ")
DEF_STRING(music_volume, "MÚSICA")
DEF_STRING(speech_volume, "VOZ")
DEF_STRING(language, "IDIOMA")
DEF_STRING(scaling_option, "GRÁFICOS")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "Não foi possível criar os arquivos de jogo. Seu HD externo está acessível?")
DEF_STRING(unable_to_create_game_files_error_dialog, "Os arquivos locais estão corrompidos. Você gostaria de fazer o download dos arquivos do jogo novamente?")
DEF_STRING(ok, "OK")
DEF_STRING(yes, "SIM")
DEF_STRING(no, "NÃO")
DEF_STRING(text_validation_failed, "Validação de arquivos de expansão falhou. O arquivo está corrompido e .precisa ser baixado novamente")
DEF_STRING(text_button_pause, "Pausa")
DEF_STRING(text_button_resume, "Retomar")
DEF_STRING(text_button_cancel, "CANCELAR")
DEF_STRING(text_button_cancel_verify, "CANCELAR")
DEF_STRING(failure_message_unknown, "Não foi possível iniciar o download dos arquivos do jogo.")
DEF_STRING(failure_message_cancelled, "O download foi cancelado.")
DEF_STRING(failure_message_connection, "Não foi possível conectar-se aos servidores do Google Play.\nPor favor tente novamente depois.")
DEF_STRING(failure_message_license, "De acordo com o Google Play, este cliente do jogo não está acessível.")
DEF_STRING(failure_message_sdcard, "Sua memória está cheia, livre um pouco de espaço.")
DEF_STRING(preparing_game_files, "Preparando os arquivos de jogo…")
DEF_STRING(cancel, "CANCELAR")
DEF_STRING(exit_confirmation_message, "Sair do jogo agora?\nProgressos não salvos serão perdidos.")
DEF_STRING(expansion_downloader_upper_text, "Baixando arquivos do jogo")
DEF_STRING(expansion_downloader_upper_text_validating, "Validando arquivos do jogo")
DEF_STRING(choose_save_slot, "ESCOLHA O ESPAÇO PARA SALVAR")
DEF_STRING(choose_load_slot, "ESCOLHA O ESPAÇO PARA CARREGAR")
DEF_STRING(enter_save_name, "Entre com o nome a ser salvo:")
DEF_STRING(save_success, "Jogo salvo com sucesso")
DEF_STRING(save_failure, "Não foi possível salvar o jogo desta vez")
DEF_STRING(load_success, "Jogo carregado com sucesso")
DEF_STRING(load_failure, "Não foi possível carregar o jogo desta vez")
DEF_STRING(load_failure_no_saves, "Não há jogos salvos disponíveis. Por favor salve o jogo primeiro.")
DEF_STRING(save_game_reminder, "O jogo está pausado - é recomendado que você salve seu jogo de tempos em tempos.")
DEF_STRING(files_fraction, "%1$s / %2$s arquivos")
DEF_STRING(save_progress_dialog, "Salvando, por favor aguarde…")
DEF_STRING(load_progress_dialog, "Carregando, por favor aguarde…")
DEF_STRING(no_saved_games, "Não há jogos salvos")
DEF_STRING(continue_, "CONTINUAR")
DEF_STRING(save_game, "SALVAR")
DEF_STRING(load_game, "CARREGAR")
DEF_STRING(new_game, "NOVO JOGO")
DEF_STRING(settings, "CONFIGURAÇÕES")
DEF_STRING(tutorial, "TUTORIAL")
DEF_STRING(game_tutorial, "Tutorial do jogo")
DEF_STRING(exit_button, "SAIR")
DEF_STRING(controls, "CONTROLES")
DEF_STRING(about, "SOBRE")
DEF_STRING(back, "VOLTAR")
DEF_STRING(menu_subtitle, "EDIÇÃO DE 25º ANNIVERSÁRIO")
DEF_STRING(shader_test_message, "Testando performance de gráficos (somente desta vez)")
DEF_STRING(rate_message, "Esperamos que tenha curtido jogar %s. Por favor avalie-nos!")
DEF_STRING(rate, "Sim, avalie agora!")
DEF_STRING(rate_later, "Lembre-me mais tarde")
DEF_STRING(rate_cancel, "Não, obrigado")
DEF_STRING(tutorial_prompt, "Você gostaria de assistir o vídeo tutorial?")
DEF_STRING(graphic_setting_message, "Para jogar de maneira suave, não aumente as configurações de gráficos - elas são baseadas na GPU de seu aparelho.")
DEF_STRING(mt32_warning_message, "Esta opção não é suportada por todos os aparelhos. Se você sentir \"quebra\" na música ou baixa performance, por favor tente reiniciar seu aparelho e escolha outra opção desta lista.")
DEF_STRING(prepare_game_files_no_space_message, "Não há espaço livre em seu aparelho.\nPor favor livre %s e então tente de novo.")
DEF_STRING(storage_unavailable, "O armazenamento de seu aparelho não está disponível - ele está conectado a um drive USB?")
DEF_STRING(new_game_confirmation, "Tem certeza que quer começar um novo jogo?\nSeu progresso não salvo será perdido.")
DEF_STRING(rate_us, "AVALIE-NOS")
DEF_STRING(store_page, "Página da loja")
DEF_STRING(share_chooser, "Compartilhar com…")
DEF_STRING(share_message, "Dá uma olhada nesse novo jogo que comprei - um clássico!")
DEF_STRING(open_house_prompt, "Isso começara um novo jogo no modo \'Casa Aberta\', que permite jogar novamente todos os quebra-cabeças no jogo para sua diversão. Continuar?")
DEF_STRING(achievement_popup_title, "Você ganhou uma conquista!")
DEF_STRING(enable_achievement_popup_checkbox, "Mostrar mensagens de conquistas")
DEF_STRING(facebook_share_achievement_btn, "Compartilhar com Facebook")
DEF_STRING(facebook_login_dialog_title, "Entre no Facebook para compartilhar suas conquistas!")
DEF_STRING(facebook_share_achievement_dialog_title, "Compartilhe suas novas conquistas em seu mural…")
DEF_STRING(facebook_share_achievement_input_hint, "Sua mensagem aqui")
DEF_STRING(facebook_share_achievement_success_toast, "A conquista foi compartilhada com sucesso")
DEF_STRING(facebook_share_achievement_failure_toast, "Houve um erro enquanto compartilhava essa conquista")
DEF_STRING(skip_english_puzzle_popup, "O quebra-cabeças a seguir é baseado em língua Inglesa, e não suporta completamente o seu idioma.\nVocê quer pular?")
DEF_STRING(microscope_puzzle_popup, "DICA: selecione uma peça, e selecione o destino para fazer com que ela se mova.")
DEF_STRING(like_view_error, "Houve um erro enquanto usava o botão Like")
DEF_STRING(error_opening_extra_file, "Não foi possível abrir o arquivo %s. Tenha certeza de que o app necessário está instalado.")
DEF_STRING(error_opening_epub_file, "Você precisa instalar um app que abra Livros (.epub files)")
DEF_STRING(achievements, "Conquistas")
DEF_STRING(extras, "Extras")
DEF_STRING(bishops_puzzle_popup, "Toque um Bispo para fazer ele se mover. Às vezes há múltiplos destinos, e as vezes o Bispo não pode mover-se de maneira alguma.")
DEF_STRING(load_change_language_popup, "Este arquivo foi salvo num idioma diferente do jogo e não pode ser usado.\nVocê gostaria de mudar para àquele idioma antes de carregar?")
DEF_STRING(no_amazon_appstore, "O Amazon Appstore inão está instalado neste aparelho")
DEF_STRING(no_sdcard, "Não foi possível acessar sua memória externa.")

END_LOCALE


BEGIN_LOCALE(ITALIAN)

DEF_STRING(no_sdcard, "Impossibile accedere al tuo disco esterno.")
DEF_STRING(prepare_game_files_no_space_message, "Non esiste spazio libero sul tuo dispositivo.\nLibera %s e riavvia.")
DEF_STRING(storage_unavailable, "Il tuo dispositivo di archiviazione è indisponibile – è connesso come USB drive?")
DEF_STRING(restart_needed, "Le tue modifiche saranno applicate dopo 'Nuova partita' o 'Carica'.")
DEF_STRING(music_mode_no_music, "Nessuno")
DEF_STRING(music_mode_original_recording, "Originale")
DEF_STRING(music_mode_enhanced, "Nuova Registrazione")
DEF_STRING(music_mode_original, "AdLib")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "General MIDI")
DEF_STRING(voice_mode_voice_subtitles, "Voce e Sottotitoli")
DEF_STRING(voice_mode_voice_only, "Solo voce")
DEF_STRING(voice_mode_subtitles_only, "Solo Sottotitoli")
DEF_STRING(subtitle_speed, "Velocità sottotitoli")
DEF_STRING(scaling_option, "GRAFICA")
DEF_STRING(scaling_option_none, "Originale")
DEF_STRING(scaling_option_software, "Basso")
DEF_STRING(scaling_option_lq_shader, "Medio")
DEF_STRING(scaling_option_shader, "Alta")
DEF_STRING(scaling_option_shader_native_res, "Ultra")
DEF_STRING(aspect_ratio_desc, "Rapporto d'aspetto:")
DEF_STRING(aspect_ratio_option_modern, "Moderno")
DEF_STRING(aspect_ratio_option_original, "Originale")
DEF_STRING(control_mode_classic, "Classico")
DEF_STRING(control_mode_classic_desc, "MOSTRA CURSORE E USA I TASTI AZIONI")
DEF_STRING(control_mode_touch, "Touch")
DEF_STRING(control_mode_touch_desc, "COMANDI BASATI SU HOTSPOTS")
DEF_STRING(control_mode_touch_classic_bar, "TOUCH CON AZIONI ORIGINALI")
DEF_STRING(music_mode, "MUSICA")
DEF_STRING(voice_mode, "VOCE")
DEF_STRING(music_volume, "MUSICA")
DEF_STRING(speech_volume, "VOCE")
DEF_STRING(language, "LINGUA")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "Impssibile creare file gioco. Il vostro disco esterno è accessibile?")
DEF_STRING(unable_to_create_game_files_error_dialog, "I file di gioco locali game sono corrotti. Vorresti eseguire il download dei file di gioco nuovamente?")
DEF_STRING(ok, "OK")
DEF_STRING(yes, "SI")
DEF_STRING(no, "NO")
DEF_STRING(text_validation_failed, "Convalida file espansione fallita. Il file è corrotto e deve essere scaricato nuovamente.")
DEF_STRING(text_button_pause, "Pausa")
DEF_STRING(text_button_resume, "Riprendi")
DEF_STRING(text_button_cancel, "ANNULLA")
DEF_STRING(text_button_cancel_verify, "ANNULLA")
DEF_STRING(cancel, "ANNULLA")
DEF_STRING(preparing_game_files, "Preparazione file gioco...")
DEF_STRING(failure_message_unknown, "Avvio download file di gioco fallito.")
DEF_STRING(failure_message_cancelled, "Il download è stato annullato.")
DEF_STRING(failure_message_connection, "Impossibile connettersi ai server Google Play.\nRiprovare più tardi.")
DEF_STRING(failure_message_license, "Secondo Google Play, questo game client è privo di licenza.")
DEF_STRING(failure_message_sdcard, "La memoria è piena, libera un po’ di spazio.")
DEF_STRING(exit_confirmation_message, "Uscire ora?\nI progressi non salvati saranno persi.")
DEF_STRING(expansion_downloader_upper_text, "Download file gioco in corso")
DEF_STRING(expansion_downloader_upper_text_validating, "Convalida file di gioco")
DEF_STRING(choose_save_slot, "Scegli posizione salvataggio")
DEF_STRING(empty_slot, "slot vuoto")
DEF_STRING(choose_load_slot, "Scegli posizione per caricare")
DEF_STRING(enter_save_name, "Inserire nome salvataggio:")
DEF_STRING(save_success, "Partita salvata con successo")
DEF_STRING(save_failure, "Impossibile salvare la partita ora")
DEF_STRING(load_success, "Partita caricata con successo")
DEF_STRING(load_failure, "Impossibile caricare adesso")
DEF_STRING(save_game_reminder, "%s è in pausa- è suggeribile salvare la tua partita di tanto in tanto.")
DEF_STRING(files_fraction, "%1$s / %2$s files")
DEF_STRING(save_progress_dialog, "Salvataggio, attendere prego...")
DEF_STRING(load_progress_dialog, "Caricamento, attendere prego...")
DEF_STRING(no_saved_games, "Non vi sono partite salvate")
DEF_STRING(continue_, "CONTINUA")
DEF_STRING(save_game, "SALVA")
DEF_STRING(load_game, "CARICA")
DEF_STRING(new_game, "NUOVA PARTITA")
DEF_STRING(settings, "IMPOSTAZIONI")
DEF_STRING(tutorial, "TUTORIAL")
DEF_STRING(game_tutorial, "Tutorial Partita")
DEF_STRING(exit_button, "ABBANDONA")
DEF_STRING(quit, "ESCI")
DEF_STRING(controls, "COMANDI")
DEF_STRING(about, "INFO")
DEF_STRING(back, "INDIETRO")
DEF_STRING(extras, "EXTRAS")
DEF_STRING(menu_subtitle, "EDIZIONE 25° ANNIVERSARIO")
DEF_STRING(shader_test_message, "Test prestazioni grafiche (solo la prima volta)")
DEF_STRING(rate_message, "Speriamo ti sia divertito giocando a %s. Votaci!")
DEF_STRING(rate, "Si, vota adesso!")
DEF_STRING(rate_later, "Ricordamelo dopo")
DEF_STRING(rate_cancel, "No, grazie")
DEF_STRING(tutorial_prompt, "Vorresti guardare il video tutorial?")
DEF_STRING(graphic_setting_message, "Per un esperienza di gioco fluida, non incrementare le impostazioni grafiche predefinite – esse si basano sulle prestazioni grafiche del tuo dispositivo (GPU).")
DEF_STRING(mt32_warning_message, "Nota che questa funzione non è supportata su tutti i dispositive. Se riscontri \"scricchiolii\" nella musica o basse prestazioni, ti preghiamo di riavviare il tuo dispositivo e scegliere una diversa opzione da questo elenco.")
DEF_STRING(new_game_confirmation, "Sei sicuro di voler iniziare una nuova partita?\nI tuoi progressi non salvati verranno persi.")
DEF_STRING(rate_us, "VOTACI")
DEF_STRING(store_page, "Vai al negozioo")
DEF_STRING(share_chooser, "Condividi con...")
DEF_STRING(share_message, "Dai un\'occhiata a questo nuovo gioco simpatico che ho appena comprato – un classico senza tempo! %s")
DEF_STRING(open_house_prompt, "Questo avvierà una nuova partita in modalità \'Open House\', cosa che ti permetterà di  rigiocare tutti i puzzles nel gioco per il tuo divertimento. Continuare?")
DEF_STRING(achievements, "Risultati")
DEF_STRING(achievement_popup_title, "Hai ottenuto un risultato! ")
DEF_STRING(enable_achievement_popup_checkbox, "Mostra finestre risultati")
DEF_STRING(facebook_share_achievement_btn, "Condividi su Facebook")
DEF_STRING(facebook_login_dialog_title, "Accedi a Facebook per condividere i risultati del tuo gioco!")
DEF_STRING(facebook_share_achievement_dialog_title, "Condividi questo nuovo risultato sulla tua bacheca...")
DEF_STRING(facebook_share_achievement_input_hint, "Il tuo messaggio qui")
DEF_STRING(facebook_share_achievement_success_toast, "Il risultato è stato condiviso con successo")
DEF_STRING(facebook_share_achievement_failure_toast, "Si è verificato un errore nella condivisione del risultato")
DEF_STRING(skip_english_puzzle_popup, "Il puzzle seguente è in Inglese, e non supporta appieno la tua lingua.\nVuoi saltarlo?")
DEF_STRING(microscope_puzzle_popup, "SUGGERIMENTO: seleziona il pezzetto nel gioco, e poi seleziona la destinazione per farlo spostare.")
DEF_STRING(like_view_error, "Si è verificato un errore durante l’utilizzo del tasto Mi Piace")
DEF_STRING(error_opening_extra_file, "Impossibile aprire il file %s. Assicurati di avere installato una app adeguata.")
DEF_STRING(error_opening_epub_file, "Devi installare una app che può aprire Libri (.epub files)")
DEF_STRING(load_change_language_popup, "Questo salvataggio è stato creato con una lingua diversa del gioco e non può essere utilizzato.\nVorresti passare a quella lingua prima di caricare?")
DEF_STRING(bishops_puzzle_popup, "Tocca un alfiere per spostarlo. A volte esistono destinazioni multiple, e a volte un alfiere non si può spostare per nulla.")
DEF_STRING(no_amazon_appstore, "Appstore Amazon non è installato su questo dispositivo")

END_LOCALE



BEGIN_LOCALE(RUSSIAN)

DEF_STRING(quit, "ВЫХОД")
DEF_STRING(no_sdcard, "Нет доступа к внешней памяти.")
DEF_STRING(restart_needed, "Изменения будут применены после запуска \'новой игры\' ИЛИ \'загрузки\'.")
DEF_STRING(music_mode_no_music, "Без музыки")
DEF_STRING(music_mode_original, "AdLib")
DEF_STRING(music_mode_original_recording, "Исходная запись")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "General MIDI")
DEF_STRING(music_mode_enhanced, "Обновленная запись")
DEF_STRING(voice_mode_voice_subtitles, "Речь и субтитры")
DEF_STRING(voice_mode_voice_only, "Только речь")
DEF_STRING(voice_mode_subtitles_only, "Только субтитры")
DEF_STRING(subtitle_speed, "Скорость субтитров")
DEF_STRING(scaling_option_lq_shader, "Средняя")
DEF_STRING(scaling_option_shader, "Высокая")
DEF_STRING(scaling_option_shader_native_res, "Ультра")
DEF_STRING(scaling_option_software, "Низкая")
DEF_STRING(scaling_option_none, "Исходная")
DEF_STRING(aspect_ratio_desc, "Соотношение сторон:")
DEF_STRING(aspect_ratio_option_modern, "Современный")
DEF_STRING(aspect_ratio_option_original, "Исходная")
DEF_STRING(control_mode_touch, "Касания")
DEF_STRING(control_mode_touch_desc, "УПРАВЛЕНИЕ С ПОМОЩЬЮ ГОРЯЧИХ ТОЧЕК")
DEF_STRING(control_mode_classic, "Классическое")
DEF_STRING(control_mode_classic_desc, "ПОКАЗЫВАТЬ КУРСОР И ИСПОЛЬЗОВАТЬ КНОПКИ ДЕЙСТВИЙ")
DEF_STRING(control_mode_touch_classic_bar, "КАСАНИЕ ПРИМЕНЯЕТ ИСХОДНЫЕ ДЕЙСТВИЯ")
DEF_STRING(music_mode, "МУЗЫКА")
DEF_STRING(voice_mode, "РЕЧЬ")
DEF_STRING(music_volume, "МУЗЫКА")
DEF_STRING(speech_volume, "РЕЧЬ")
DEF_STRING(language, "ЯЗЫК")
DEF_STRING(scaling_option, "ГРАФИКА")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "Невозможно создать игровые файлы. Ваша внешняя память доступна для записи?")
DEF_STRING(unable_to_create_game_files_error_dialog, "Файлы игры на устройстве испорчены. Вы хотите заново загрузить игровые файлы?")
DEF_STRING(ok, "OK")
DEF_STRING(yes, "ДА")
DEF_STRING(no, "НЕТ")
DEF_STRING(text_validation_failed, "Не удалось проверить файлы дополнения. Файл испорчен, требуется его перезагрузить.")
DEF_STRING(text_button_pause, "Пауза")
DEF_STRING(text_button_resume, "Возобновить игру")
DEF_STRING(text_button_cancel, "ОТМЕНА")
DEF_STRING(text_button_cancel_verify, "ОТМЕНА")
DEF_STRING(failure_message_unknown, "Не удалось начать загрузку игровых файлов.")
DEF_STRING(failure_message_cancelled, "Скачивание было отменено.")
DEF_STRING(failure_message_connection, "Не удалось подключиться к серверам Google Play.\nПожалуйста, попробуйте ещё раз позже.")
DEF_STRING(failure_message_license, "Google Play считает, что эта программа по запуску игры нелицензирована.")
DEF_STRING(failure_message_sdcard, "Память заполнена, освободите немного места.")
DEF_STRING(preparing_game_files, "Идёт подготовка игровых файлов...")
DEF_STRING(cancel, "ОТМЕНА")
DEF_STRING(exit_confirmation_message, "Выйти из игры сейчас?\nНесохраненные изменения будут потеряны.")
DEF_STRING(expansion_downloader_upper_text, "Идёт загрузка игровых файлов")
DEF_STRING(expansion_downloader_upper_text_validating, "Идёт проверка игровых файлов")
DEF_STRING(choose_save_slot, "ВЫБЕРИТЕ ЯЧЕЙКУ СОХРАНЕНИЯ")
// DEF_STRING(empty_slot, "Пустая ячейка") - save game names doesn't take non latin chars
DEF_STRING(choose_load_slot, "ВЫБЕРИТЕ ЯЧЕЙКУ ДЛЯ ЗАГРУЗКИ")
DEF_STRING(enter_save_name, "Введите имя сохранения:")
DEF_STRING(save_success, "Игра успешно сохранена")
DEF_STRING(save_failure, "Невозможно сохранить игру сейчас. Пожалуйста, попробуйте ещё раз в другой комнате или в другое время.")
DEF_STRING(load_success, "Игра успешно загружена")
DEF_STRING(load_failure, "Невозможно загрузить игру сейчас")
DEF_STRING(load_failure_no_saves, "Нет доступных сохранений. Пожалуйста, сначала сохранитесь.")
DEF_STRING(save_game_reminder, "Игра приостановлена - рекомендуем время от времени сохраняться.")
DEF_STRING(files_fraction, "%1$s / %2$s файлов")
DEF_STRING(save_progress_dialog, "Игра сохраняется, пожалуйста, подождите...")
DEF_STRING(load_progress_dialog, "Игра загружается, пожалуйста, подождите...")
DEF_STRING(no_saved_games, "Нет сохранённых игр")
DEF_STRING(continue_, "ПРОДОЛЖИТЬ")
DEF_STRING(save_game, "СОХРАНИТЬ")
DEF_STRING(load_game, "ЗАГРУЗИТЬ")
DEF_STRING(new_game, "НОВАЯ ИГРА")
DEF_STRING(settings, "НАСТРОЙКИ")
DEF_STRING(tutorial, "ОБУЧЕНИЕ")
DEF_STRING(game_tutorial, "Введение в игру")
DEF_STRING(exit_button, "ВЫХОД")
DEF_STRING(controls, "УПРАВЛЕНИЕ")
DEF_STRING(about, "ОБ ИГРЕ")
DEF_STRING(back, "НАЗАД")
DEF_STRING(menu_subtitle, "ЮБИЛЕЙНОЕ ИЗДАНИЕ К ДВАДЦАТИЛЕТИЮ ИГРЫ")
DEF_STRING(shader_test_message, "Проверка производительности графической системы (только при первом запуске)")
DEF_STRING(rate_message, "Мы надеемся, что вам понравилось играть в %s. Пожалуйста, поставьте оценку!")
DEF_STRING(rate, "Да, оценить игру сейчас!")
DEF_STRING(rate_later, "Напомнить позже")
DEF_STRING(rate_cancel, "Нет, спасибо")
DEF_STRING(tutorial_prompt, "Хотите посмотреть обучающий видеоролик?")
DEF_STRING(graphic_setting_message, "Для плавного движения в игре не увеличивайте графические настройки по умолчанию - они выставлены в соответствии с графическими возможностями вашего устройства (GPU).")
DEF_STRING(mt32_warning_message, "Пожалуйста, обратите внимание, что эта возможность доступна не на всех устройствах. Если вы слышите прерывания при воспроизведении музыки, игра идёт медленно, попробуйте перегрузить ваше устройство и выбрать другой вариант из данного списка.")
DEF_STRING(prepare_game_files_no_space_message, "На вашем устройстве нет свободного места.\nПожалуйста, освободите %s и попробуйте ещё раз.")
DEF_STRING(storage_unavailable, "Память вашего устройства не доступна - она подключена как USB диск?")
DEF_STRING(new_game_confirmation, "Вы уверены, что хотите начать новую игру?\nНесохраненные изменения будут потеряны.")
DEF_STRING(rate_us, "ОЦЕНИТЕ НАС")
DEF_STRING(store_page, "Страница магазина")
DEF_STRING(share_chooser, "Поделиться с...")
DEF_STRING(share_message, "Посмотри, какую классную новую игру я приобрёл - это же бессмертная классика!")
DEF_STRING(open_house_prompt, "Эта опция начнёт новую игру в режиме \'Открытый дом\'. В этом режиме вы сможете перепройти все загадки в игре для своего удовольствия. Продолжить?")
DEF_STRING(achievement_popup_title, "Вы получили новое достижение!")
DEF_STRING(enable_achievement_popup_checkbox, "Показывать всплывающие сообщения о достижениях")
DEF_STRING(facebook_share_achievement_btn, "Поделиться в Facebook")
DEF_STRING(facebook_login_dialog_title, "Авторизируйтесь в Facebook, чтобы поделиться своими достижениями в игре!")
DEF_STRING(facebook_share_achievement_dialog_title, "Опубликовать новое достижение на своей стене...")
DEF_STRING(facebook_share_achievement_input_hint, "Напишите здесь своё сообщение")
DEF_STRING(facebook_share_achievement_success_toast, "Достижение было успешно опубликовано")
DEF_STRING(facebook_share_achievement_failure_toast, "При опубликовании достижения произошла ошибка")
DEF_STRING(skip_english_puzzle_popup, "Следующая загадка основана на знании английского языка, она не поддерживается в полной мере при выборе вашего языка.\nХотите ли ее пропустить?")
DEF_STRING(microscope_puzzle_popup, "ПОДСКАЗКА: выберите кусочек игры, а затем выберите куда поместить, и он переместится.")
DEF_STRING(like_view_error, "Произошла ошибка при использовании кнопки \'Мне нравится\'")
DEF_STRING(error_opening_extra_file, "Невозможно открыть файл %s. Убедитесь, что у вас есть подходящая программа для запуска.")
DEF_STRING(error_opening_epub_file, "Вам необходима программа, которая может открывать Книги (файлы .epub)")
DEF_STRING(achievements, "Достижения")
DEF_STRING(extras, "Дополнения")
DEF_STRING(bishops_puzzle_popup, "Коснитесь слона, чтобы его переместить. Иногда доступно несколько положений для перемещения, а иногда слон совсем не может перемещаться.")
DEF_STRING(load_change_language_popup, "Это сохранение было сделано с другим языком игры и не может быть использовано.\nХотите выбрать этот язык и загрузить игру?")
DEF_STRING(no_amazon_appstore, "Магазин приложений Amazon не установлен на этом устройстве")

END_LOCALE



BEGIN_LOCALE(SWEDISH)

DEF_STRING(quit, "AVSLUTA")
DEF_STRING(no_sdcard, "KAN INTE ÖPPNA EXTERN LAGERENHET.")
DEF_STRING(restart_needed, "DINA ÄNDRINGAR BLIR GÄLLANDE EFTER \'NYTT SPEL\' ELLER \'LADDA\'.")
DEF_STRING(music_mode_no_music, "INGEN")
DEF_STRING(music_mode_original, "ADLIB")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "GENERAL MIDI")
DEF_STRING(music_mode_enhanced, "NY INSPELNING")
DEF_STRING(voice_mode_voice_subtitles, "RÖSTER OCH UNDERTEXTER")
DEF_STRING(voice_mode_voice_only, "ENDAST RÖSTER")
DEF_STRING(voice_mode_subtitles_only, "ENDAST UNDERTEXTER")
DEF_STRING(scaling_option_lq_shader, "MEDEL")
DEF_STRING(scaling_option_shader, "HÖG")
DEF_STRING(scaling_option_shader_native_res, "ULTRA")
DEF_STRING(scaling_option_software, "LÅG")
DEF_STRING(scaling_option_none, "ORIGINAL")
DEF_STRING(aspect_ratio_desc, "Bildförhållande:")
DEF_STRING(aspect_ratio_option_modern, "MODERN")
DEF_STRING(aspect_ratio_option_original, "ORIGINAL")
DEF_STRING(control_mode_touch, "TOUCH")
DEF_STRING(control_mode_touch_classic_bar, "TOUCH MED ORIGINALÅTGÄRDER")
DEF_STRING(control_mode_classic, "KLASSISKT")
DEF_STRING(music_mode, "MUSIK")
DEF_STRING(voice_mode, "RÖSTER")
DEF_STRING(music_volume, "MUSIK")
DEF_STRING(speech_volume, "RÖSTER")
DEF_STRING(language, "SPRÅK")
DEF_STRING(scaling_option, "GRAFIK")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "Kunde inte skapa spelfiler. Är din externa lagerenhet ansluten?")
DEF_STRING(unable_to_create_game_files_error_dialog, "De lokala spelfilerna är korrupta. Vill du ladda ned spelfilerna igen?")
DEF_STRING(ok, "OK")
DEF_STRING(yes, "JA")
DEF_STRING(no, "NEJ")
DEF_STRING(text_validation_failed, "Verifieringen av expansionsfilen misslyckades. Filen är korrupt och måste laddas ned igen.")
DEF_STRING(text_button_pause, "PAUS")
DEF_STRING(text_button_resume, "FORTSÄTT")
DEF_STRING(text_button_cancel, "AVBRYT")
DEF_STRING(text_button_cancel_verify, "AVBRYT")
DEF_STRING(failure_message_unknown, "KUNDE INTE LADDA NED SPELFILER.")
DEF_STRING(failure_message_cancelled, "NEDLADDNINGEN AVBRÖTS.")
DEF_STRING(failure_message_connection, "KUNDE INTE ANSLUTA TILL GOOGLE PLAYS SERVRAR.\nVAR GOD FÖRSÖK IGEN SENARE.")
DEF_STRING(failure_message_license, "ENLIGT GOOGLE PLAY ÄR DEN HÄR SPELKLIENTEN INTE LICENSIERAD.")
DEF_STRING(failure_message_sdcard, "LAGRET ÄR FULLT, FRIGÖR LITE MER UTRYMME.")
DEF_STRING(preparing_game_files, "FÖRBEREDER SPELFILER...")
DEF_STRING(cancel, "AVBRYT")
DEF_STRING(exit_confirmation_message, "VILL DU AVSLUTA NU?\n\nFRAMSTEG SOM INTE SPARATS KOMMER ATT FÖRLORAS.")
DEF_STRING(expansion_downloader_upper_text, "LADDAR NED SPELFILER")
DEF_STRING(expansion_downloader_upper_text_validating, "VERIFIERAR SPELFILER")
DEF_STRING(choose_save_slot, "VÄLJ SPARPLATS")
DEF_STRING(empty_slot, "tom plats")
DEF_STRING(choose_load_slot, "VÄLJ PLATS ATT LADDA")
DEF_STRING(enter_save_name, "ANGE NAMN FÖR SPARAD DATA:")
DEF_STRING(save_success, "Spelet sparades")
DEF_STRING(save_failure, "Kunde inte spara spelet just nu")
DEF_STRING(load_success, "Spelet laddades")
DEF_STRING(load_failure, "Kunde inte ladda spelet just nu")
DEF_STRING(save_game_reminder, "Spel är pausat - det rekommenderas att du sparar ditt spel då och då.")
DEF_STRING(files_fraction, "%1$s / %2$s filer")
DEF_STRING(save_progress_dialog, "SPARAR, VAR GOD VÄNTA...")
DEF_STRING(load_progress_dialog, "LADDAR, VAR GOD VÄNTA...")
DEF_STRING(no_saved_games, "Det finns inga sparade data")
DEF_STRING(continue_, "FORTSÄTT")
DEF_STRING(save_game, "SPARA")
DEF_STRING(load_game, "LADDA")
DEF_STRING(new_game, "NYTT SPEL")
DEF_STRING(settings, "INSTÄLLNINGAR")
DEF_STRING(tutorial, "GENOMGÅNG")
DEF_STRING(game_tutorial, "GENOMGÅNG AV SPEL")
DEF_STRING(exit_button, "AVSLUTA")
DEF_STRING(controls, "KONTROLLER")
DEF_STRING(about, "INFORMATION")
DEF_STRING(back, "TILLBAKA")
DEF_STRING(shader_test_message, "Testar grafisk prestanda (endast första gången)")
DEF_STRING(rate_message, "Vi hoppas du gillar att spela %s. Betygsätt det gärna!")
DEF_STRING(rate, "BETYGSÄTT NU!")
DEF_STRING(rate_later, "PÅMINN MIG SENARE")
DEF_STRING(rate_cancel, "NEJ, TACK")
DEF_STRING(tutorial_prompt, "VILL DU SE GENOMGÅNGSVIDEON?")
DEF_STRING(graphic_setting_message, "För en smidig spelupplevelse bör du inte justera de grafiska inställningarna - de är baserade på din enhets grafiska prestanda (GPU).")
DEF_STRING(mt32_warning_message, "Observera att den här funktionen inte stöds på alla enheter. Om du upplever brus i musiken eller dålig prestanda, försök att starta om din enhet och välj ett annat alternativ från den här listan.")
DEF_STRING(prepare_game_files_no_space_message, "DET FINNS INTE TILLRÄCKLIGT MED LEDIGT UTRYMME PÅ DIN ENHET. \nFRIGÖR UPP TILL %s UTRYMME OCH FÖRSÖK IGEN.")
DEF_STRING(storage_unavailable, "DIN LAGERENHET ÄR INTE TILLGÄNGLIG - ÄR DEN ANSLUTEN SOM EN USB-ENHET?")
DEF_STRING(new_game_confirmation, "ÄR DU SÄKER PÅ ATT DU VILL BÖRJA ETT NYTT SPEL?\nFRAMSTEG SOM INTE SPARATS KOMMER ATT FÖRLORAS.")
DEF_STRING(rate_us, "BETYGSÄTT OSS")
DEF_STRING(store_page, "Butikssida")

END_LOCALE


BEGIN_LOCALE(POLISH)

DEF_STRING(restart_needed, "Wprowadzone zmiany zostaną zastosowane po uruchomieniu nowej gry lub wczytaniu zapisanego stanu gry.")
DEF_STRING(music_mode_no_music, "Brak")
DEF_STRING(music_mode_original, "AdLib")
DEF_STRING(music_mode_original_recording, "Oryginalna")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(mt32_warning_message, "Funkcja ta nie jest wspierana na wszystkich urządzeniach. Jeśli usłyszysz trzaski lub zauważysz wolne działanie gry, spróbuj zrestartować swoje urządzenie i wybierz inną pozycję z tej listy.")
DEF_STRING(music_mode_original_eas, "General MIDI (EAS)")
DEF_STRING(music_mode_original_general_midi, "General MIDI")
DEF_STRING(music_mode_enhanced, "Nowe nagrania")
DEF_STRING(voice_mode_voice_subtitles, "Dubbing i napisy")
DEF_STRING(voice_mode_voice_only, "Tylko dubbing")
DEF_STRING(voice_mode_subtitles_only, "Tylko napisy")
DEF_STRING(subtitle_speed, "Szybkość napisów")
DEF_STRING(scaling_option_lq_shader, "Średnia jakość")
DEF_STRING(scaling_option_shader, "Wysoka jakość")
DEF_STRING(scaling_option_shader_native_res, "Najwyższa jakość")
DEF_STRING(scaling_option_software, "Niska jakość")
DEF_STRING(scaling_option_none, "Oryginalna")
DEF_STRING(aspect_ratio_desc, "Format obrazu:")
DEF_STRING(aspect_ratio_option_modern, "Współczesny")
DEF_STRING(aspect_ratio_option_original, "Oryginalny")
DEF_STRING(control_mode_touch, "Dotykowe")
DEF_STRING(control_mode_touch_desc, "STEROWANIE OPARTE NA AKTYWNYCH MIEJSCACH")
DEF_STRING(control_mode_classic, "Klasyczne")
DEF_STRING(control_mode_classic_desc, "STEROWANIE OPARTE NA KURSORZE I PRZYCISKACH AKCJI")
DEF_STRING(control_mode_touch_classic_bar, "DOTYKOWE Z ORYGINALNYMI AKCJAMI")
DEF_STRING(control_mode_enhanced_desktop, "Ulepszone")
DEF_STRING(control_mode_enhanced_desktop_classic_bar, "Ulepszone z oryginalnymi akcjami")
DEF_STRING(music_mode, "MUZYKA")
DEF_STRING(voice_mode, "DUBBING")
DEF_STRING(music_volume, "MUZYKA")
DEF_STRING(speech_volume, "DUBBING")
DEF_STRING(language, "JĘZYK")
DEF_STRING(scaling_option, "GRAFIKA")
DEF_STRING(ok, "OK")
DEF_STRING(yes, "TAK")
DEF_STRING(no, "NIE")
DEF_STRING(text_validation_failed, "Sprawdzanie pliku rozszerzenia zakończyło się niepowodzeniem. Plik jest uszkodzony i wymaga ponownego pobrania.")
DEF_STRING(text_button_pause, "Pauza")
DEF_STRING(text_button_resume, "Wznów")
DEF_STRING(text_button_cancel, "ANULUJ")
DEF_STRING(text_button_cancel_verify, "ANULUJ")
DEF_STRING(failure_message_unknown, "Próba rozpoczęcia pobierania gry zakończyła się niepowodzeniem.")
DEF_STRING(failure_message_cancelled, "Pobieranie zostało anulowane.")
DEF_STRING(failure_message_connection, "Nie udało się nawiązać połączenia z serwerami Google Play.\nProszę spróbować później.")
DEF_STRING(failure_message_license, "Według Google Play ten klient gry nie posiada licencji.")
DEF_STRING(failure_message_sdcard, "Brak wolnego miejsca. Należy zwolnić część wykorzystywanej przestrzeni.")
DEF_STRING(preparing_game_files, "Przygotowywanie plików gry...")
DEF_STRING(cancel, "ANULUJ")
DEF_STRING(exit_confirmation_message, "Czy chcesz opuścić grę?\nNiezapisane postępy zostaną utracone.")
DEF_STRING(expansion_downloader_upper_text, "Pobieranie plików gry")
DEF_STRING(expansion_downloader_upper_text_validating, "Sprawdzanie plików gry")
DEF_STRING(choose_save_slot, "WYBIERZ MIEJSCE NA ZAPIS")
DEF_STRING(choose_load_slot, "WYBIERZ ZAPIS, KTÓRY ZOSTANIE WCZYTANY")
DEF_STRING(enter_save_name, "Wprowadź nazwę zapisu:")
DEF_STRING(save_success, "Zapis stanu gry zakończony powodzeniem")
DEF_STRING(save_failure, "Nie udało się zapisać stanu gry")
DEF_STRING(load_success, "Wczytanie stanu gry zakończone powodzeniem")
DEF_STRING(load_failure, "Nie udało się wczytać stanu gry")
DEF_STRING(load_failure_no_saves, "Brak zapisów stanu gry. Przed wczytaniem stanu gry, należy utworzyć jego zapis.")
DEF_STRING(save_game_reminder, "Gra wstrzymana - od czasu do czasu warto wykonywać zapisy stanu gry.")
DEF_STRING(files_fraction, "%1$s / %2$s plików")
DEF_STRING(save_progress_dialog, "Zapisywanie, proszę czekać...")
DEF_STRING(load_progress_dialog, "Wczytywanie, proszę czekać...")
DEF_STRING(no_saved_games, "Brak zapisów stanu gry")
DEF_STRING(continue_, "KONTYNUUJ")
DEF_STRING(save_game, "ZAPISZ")
DEF_STRING(load_game, "WCZYTAJ")
DEF_STRING(new_game, "NOWA GRA")
DEF_STRING(settings, "USTAWIENIA")
DEF_STRING(tutorial, "SAMOUCZEK")
DEF_STRING(game_tutorial, "Samouczek")
DEF_STRING(achievements, "Osiągnięcia")
DEF_STRING(extras, "Dodatki")
DEF_STRING(quit, "WYJŚCIE")
DEF_STRING(exit_button, "ZAKOŃCZ")
DEF_STRING(controls, "STEROWANIE")
DEF_STRING(about, "O GRZE")
DEF_STRING(back, "WSTECZ")
DEF_STRING(menu_subtitle, "EDYCJA Z OKAZJI 25-LECIA")
DEF_STRING(shader_test_message, "Sprawdzanie wydajności graficznej (tylko przy pierwszym uruchomieniu)")
DEF_STRING(rate_message, "Mamy nadzieję, że podobała ci się zabawa w %s. Prosimy o ocenę naszej gry!")
DEF_STRING(rate, "Tak, oceń teraz!")
DEF_STRING(rate_later, "Przypomnij mi później")
DEF_STRING(rate_cancel, "Nie, dzięki")
DEF_STRING(tutorial_prompt, "Czy chcesz obejrzeć samouczek?")
DEF_STRING(graphic_setting_message, "Aby cieszyć się płynną rozgrywką, nie zwiększaj domyślnych ustawień grafiki - zostały dopasowane do wydajności twojego urządzenia (GPU).")
DEF_STRING(new_game_confirmation, "Czy na pewno chcesz rozpocząć nową grę?\nNiezapisane postępy zostaną utracone.")
DEF_STRING(rate_us, "OCEŃ NAS")
DEF_STRING(store_page, "Strona w sklepie")
DEF_STRING(share_chooser, "Udostępnij na...")
DEF_STRING(share_message, "Zobaczcie, jaką fajną grę udało mi się właśnie kupić - nieśmiertelny klasyk!")
DEF_STRING(open_house_prompt, "Dzięki tej opcji rozpoczniesz nową grę w trybie \"Otwartego domu\", który umożliwia ponowne rozegranie wszystkich łamigłówek. Kontynuować?")
DEF_STRING(achievement_popup_title, "Udało ci się zdobyć osiągnięcie!")
DEF_STRING(enable_achievement_popup_checkbox, "Pokaż powiadomienia o osiągnięciach")
DEF_STRING(skip_english_puzzle_popup, "Rozwiązanie łamigłówki wymaga znajomości języka angielskiego.\nCzy chcesz ją pominąć?")
DEF_STRING(microscope_puzzle_popup, "PODPOWIEDŹ: Wybierz pionek, a następnie miejsce, w które chcesz go przesunąć.")
DEF_STRING(bishops_puzzle_popup, "Dotknij gońca, aby go przesunąć. Czasem można go przesunąć na wiele różnych pól, a czasem goniec jest zablokowany i nie może zmienić swojego położenia.")
DEF_STRING(load_change_language_popup, "Ten zapis stworzono, gdy w grze był ustawiony inny język, przez co nie można go użyć.\nCzy chcesz zmienić język w grze na odpowiadający językowi zapisu, aby można go było wczytać?")
DEF_STRING(no_amazon_appstore, "Na tym urządzeniu nie zainstalowano aplikacji Amazon Appstore")
DEF_STRING(like_view_error, "Podczas próby użycia przycisku \"Lubię to\" doszło do awarii")
DEF_STRING(error_opening_extra_file, "Nie udało się otworzyć pliku %s. Upewnij się, że masz zainstalowaną odpowiednią aplikację.")
DEF_STRING(error_opening_epub_file, "Musisz zainstalować aplikację umożliwiającą otwieranie elektronicznych książek (plików .epub)")
DEF_STRING(no_sdcard, "Nie można uzyskać dostępu do pamięci zewnętrznej.")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "Próba utworzenia plików gry zakończyła się niepowodzeniem. Czy twoja zewnętrzna pamięć jest dostępna?")
DEF_STRING(unable_to_create_game_files_error_dialog, "Pliki gry na twoim urządzeniu są uszkodzone. Czy chcesz pobrać je ponownie?")
DEF_STRING(storage_unavailable, "Pamięć masowa twojego urządzenia jest niedostępna - czy jest podłączona jako napęd USB?")
DEF_STRING(prepare_game_files_no_space_message, "Na twoim urządzeniu brakuje wolnego miejsca.\nPostaraj się zwolnić %s i spróbuj ponownie.")

END_LOCALE


BEGIN_LOCALE(HEBREW)

#ifndef WIN32
           
DEF_STRING(quit, "יציאה")
DEF_STRING(no_sdcard, "לא ניתן לגשת לאחסון חיצוני.")
DEF_STRING(restart_needed, "השינויים יכנסו לתוקף אחרי \'משחק חדש\' או \'טעינה\'.")
DEF_STRING(music_mode_no_music, "ללא")
DEF_STRING(music_mode_original, "ADLIB")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "GENERAL MIDI (EAS)")
DEF_STRING(music_mode_enhanced, "הקלטה חדשה")
DEF_STRING(voice_mode_voice_subtitles, "קול וכתוביות")
DEF_STRING(voice_mode_voice_only, "קול בלבד")
DEF_STRING(voice_mode_subtitles_only, "כתוביות בלבד")
DEF_STRING(scaling_option_lq_shader, "בינונית")
DEF_STRING(scaling_option_shader, "גבוהה")
DEF_STRING(scaling_option_shader_native_res, "אולטרה")
DEF_STRING(scaling_option_software, "נמוכה")
DEF_STRING(scaling_option_none, "מקורית")
DEF_STRING(aspect_ratio_desc, "יחס תמונה:")
DEF_STRING(aspect_ratio_option_modern, "מודרני")
DEF_STRING(aspect_ratio_option_original, "מקורי")
DEF_STRING(control_mode_touch, "מגע")
DEF_STRING(control_mode_touch_classic_bar, "מגע עם פעולות מקוריות")
DEF_STRING(control_mode_classic, "מקורי")
DEF_STRING(sfx_volume, "אפקטים")
DEF_STRING(music_mode, "מוזיקה")
DEF_STRING(voice_mode, "קול")
DEF_STRING(music_volume, "מוזיקה")
DEF_STRING(speech_volume, "קול")
DEF_STRING(language, "שפה")
DEF_STRING(scaling_option, "גרפיקה")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "לא ניתן לייצר קבצי משחק. האם התקן האחסון שלך זמין ?")
DEF_STRING(unable_to_create_game_files_error_dialog, "קבצי המשחק המקומיים תקולים. האם תרצה להוריד אותם מחדש ?")
DEF_STRING(ok, "אישור")
DEF_STRING(yes, "כן")
DEF_STRING(no, "לא")
DEF_STRING(text_validation_failed, "אימות קובץ הרחבה נכשל. הקובץ לא תקין ויש צורך להורידו שוב.")
DEF_STRING(text_button_pause, "הפסק")
DEF_STRING(text_button_resume, "המשך")
DEF_STRING(text_button_cancel, "ביטול")
DEF_STRING(text_button_cancel_verify, "ביטול")
DEF_STRING(failure_message_unknown, "הורדת קבצי משחק נכשלה.")
DEF_STRING(failure_message_cancelled, "ההורדה בוטלה.")
DEF_STRING(failure_message_connection, "לא ניתן להתחבר לשרתי GOOGLE PLAY.\nאנא נסה שנית מאוחר יותר.")
DEF_STRING(failure_message_license, "על פי שרתי GOOGLE PLAY, משחק זה לא נקנה מהחנות.")
DEF_STRING(failure_message_sdcard, "אחסון מלא, אנא פנה קצת מקום")
DEF_STRING(preparing_game_files, "מכין קבצי משחק...")
DEF_STRING(cancel, "ביטול")
DEF_STRING(exit_confirmation_message, "זהו הולכים? רק זכרו לשמור את המשחק.\n\nנשמח לראותכם שוב!")
DEF_STRING(expansion_downloader_upper_text, "מוריד קבצי משחק")
DEF_STRING(expansion_downloader_upper_text_validating, "אימות קבצי משחק")
DEF_STRING(choose_save_slot, "בחר משחק לשמירה")
// DEF_STRING(empty_slot, "מקום פנוי") - save game names doesn't take non latin chars
DEF_STRING(choose_load_slot, "בחר משחק לטעינה")
DEF_STRING(enter_save_name, "הכנס שם לשמירה:")
DEF_STRING(save_success, "שמירת משחק בוצעה בהצלחה")
DEF_STRING(save_failure, "לא ניתן לשמור את המשחק בזמן זה")
DEF_STRING(load_success, "טעינת משחק בוצעה בהצלחה")
DEF_STRING(load_failure, "לא ניתן לטעון את המשחק בזמן זה")
DEF_STRING(save_game_reminder, "המשחק מושהה - מומלץ לבצע שמירת משחק מפעם לפעם.")
DEF_STRING(files_fraction, "%1$ / %2$ קבצים")
DEF_STRING(save_progress_dialog, "שומר, אנא המתן...")
DEF_STRING(load_progress_dialog, "טוען, אנא המתן...")
DEF_STRING(no_saved_games, "אין שמירות")
DEF_STRING(continue_, "המשך")
DEF_STRING(save_game, "שמירה")
DEF_STRING(load_game, "טעינה")
DEF_STRING(new_game, "משחק חדש")
DEF_STRING(settings, "הגדרות")
DEF_STRING(tutorial, "הדרכה")
DEF_STRING(game_tutorial, "הדרכה")
DEF_STRING(exit_button, "יציאה")
DEF_STRING(controls, "ממשק משתמש")
DEF_STRING(about, "אודות")
DEF_STRING(back, "חזרה")
DEF_STRING(menu_subtitle, "מהדורת שנת ה-25")
DEF_STRING(shader_test_message, "בודק ביצועי גרפיקה (פעם ראשונה בלבד)")
DEF_STRING(rate_message, "אנחנו מקווים שנהנת לשחק ב%s. בבקשה דרג אותנו!")
DEF_STRING(rate, "כן, דרג עכשיו!")
DEF_STRING(rate_later, "הזכר לי מאוחר יותר")
DEF_STRING(rate_cancel, "לא, תודה")
DEF_STRING(tutorial_prompt, "תרצה לראות את סרטון ההדרכה ?")
DEF_STRING(graphic_setting_message, "לחווית משחק חלקה, אל תבחר הגדרת גרפיקה גבוהה יותר מברירת המחדל - היא מבוססת על היכולות הגרפיות של מכשירך (GPU).")
DEF_STRING(mt32_warning_message, "אנא שים לב שאפשרות זו לא נתמכת על כל המכשירים. אם אתה חווה  הפרעות במוזיקה או ביצועים נמוכים, אנא נסה להפעיל מחדש את מכשירך ולבחור אפשרות אחרת מרשימה זו.")
DEF_STRING(prepare_game_files_no_space_message, "אין מספיק מקום על מכשירך. אנא פנה לפחות %s ונסה שוב.")
DEF_STRING(storage_unavailable, "התקן האחסון של מכשירך לא זמין - האם הוא מחובר כהתקן USB ?")
DEF_STRING(new_game_confirmation, "מתחילים מחדש? רק זכרו לשמור את המשחק.\n\nמשחק מהנה!")
DEF_STRING(rate_us, "דרג אותנו")
DEF_STRING(store_page, "דף החנות")
DEF_STRING(extras, "תוספות")
DEF_STRING(error_opening_epub_file, "אתה צריך להתקין אפליקציה שיכולה לפתוח ספרים (קבצי .epub)")
DEF_STRING(subtitle_speed, "מהירות כתוביות")
DEF_STRING(share_chooser, "שתף עם...")
DEF_STRING(share_message, "תראו איזה משחק מגניב קניתי הרגע - קלאסיקה נצחית!")
DEF_STRING(open_house_prompt, "אתם מתחילים משחק חדש במצב 'בית פתוח', שיאפשר לכם לשחק מחדש בכל הפאזלים במשחק להנאתכם. להמשיך?")
DEF_STRING(skip_english_puzzle_popup, "הפאזל הבא מבוסס אנגלית, ולא תומך בשפה שלכם באופן מלא. תרצו לדלג עליו?")
DEF_STRING(microscope_puzzle_popup, "טיפ: בחר את כלי המשחק, ואז בחר ביעד כדי להזיז אותו.")
DEF_STRING(bishops_puzzle_popup, "גע ברץ בכדי להזיז אותו. לפעמים ישנם כמה יעדים, ולפעמים הרץ לא יכול לזוז בכלל.")
DEF_STRING(achievements, "הישגים")
DEF_STRING(achievement_popup_title, "זכית בהישג!")
DEF_STRING(enable_achievement_popup_checkbox, "הצג רשימת הישגים")
DEF_STRING(facebook_share_achievement_btn, "שתף בפייסבוק")
DEF_STRING(facebook_login_dialog_title, "התחבר לפייסבוק על מנת לשתף את הישגיך במשחק!")
DEF_STRING(facebook_share_achievement_dialog_title, "שתף את ההישג החדש בקיר שלך...")
DEF_STRING(facebook_share_achievement_input_hint, "המסר שלך כאן")
DEF_STRING(facebook_share_achievement_success_toast, "ההישג שותף בהצלחה")
DEF_STRING(facebook_share_achievement_failure_toast, "אירעה תקלה כששיתפת את ההישג")
DEF_STRING(like_view_error, "אירעה תקלה כשלחצת על כפתור הלייק")
DEF_STRING(error_opening_extra_file, "אנחנו לא מצליחים לפתוח את הקובץ %s. וודא שמותקן אצלך היישום המתאים.")
DEF_STRING(load_change_language_popup, "השמירה הזאת נוצרה עבור שפה אחרת במשחק ולא ניתן להשתמש בה. התרצה לעבור לאותה שפה לפני הטעינה?")
DEF_STRING(no_amazon_appstore, "חנות היישומים של אמזון לא מותקנת במכשיר הזה")
DEF_STRING(control_mode_enhanced_desktop, "משופר")
DEF_STRING(control_mode_enhanced_desktop_classic_bar, "משופר עם הפקודות המקוריות")

#else

DEF_STRING(quit, "יציאה")
DEF_STRING(no_sdcard, ".לא ניתן לגשת לאחסון חיצוני")
DEF_STRING(restart_needed, ".השינויים יכנסו לתוקף אחרי \'משחק חדש\' או \'טעינה\'")
DEF_STRING(music_mode_no_music, "ללא")
DEF_STRING(music_mode_original, "ADLIB")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "GENERAL MIDI (EAS)")
DEF_STRING(music_mode_enhanced, "הקלטה חדשה")
DEF_STRING(voice_mode_voice_subtitles, "קול וכתוביות")
DEF_STRING(voice_mode_voice_only, "קול בלבד")
DEF_STRING(voice_mode_subtitles_only, "כתוביות בלבד")
DEF_STRING(scaling_option_lq_shader, "בינונית")
DEF_STRING(scaling_option_shader, "גבוהה")
DEF_STRING(scaling_option_shader_native_res, "אולטרה")
DEF_STRING(scaling_option_software, "נמוכה")
DEF_STRING(scaling_option_none, "מקורית")
DEF_STRING(aspect_ratio_desc, ":יחס תמונה")
DEF_STRING(aspect_ratio_option_modern, "מודרני")
DEF_STRING(aspect_ratio_option_original, "מקורי")
DEF_STRING(control_mode_touch, "מגע")
DEF_STRING(control_mode_touch_classic_bar, "מגע עם פעולות מקוריות")
DEF_STRING(control_mode_classic, "מקורי")
DEF_STRING(sfx_volume, "אפקטים")
DEF_STRING(music_mode, "מוזיקה")
DEF_STRING(voice_mode, "קול")
DEF_STRING(music_volume, "מוזיקה")
DEF_STRING(speech_volume, "קול")
DEF_STRING(language, "שפה")
DEF_STRING(scaling_option, "גרפיקה")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "?לא ניתן לייצר קבצי משחק. האם התקן האחסון שלך זמין")
DEF_STRING(unable_to_create_game_files_error_dialog, "?קבצי המשחק המקומיים תקולים. האם תרצה להוריד אותם מחדש")
DEF_STRING(ok, "אישור")
DEF_STRING(yes, "כן")
DEF_STRING(no, "לא")
DEF_STRING(text_validation_failed, ".אימות קובץ הרחבה נכשל. הקובץ לא תקין ויש צורך להורידו שוב")
DEF_STRING(text_button_pause, "הפסק")
DEF_STRING(text_button_resume, "המשך")
DEF_STRING(text_button_cancel, "ביטול")
DEF_STRING(text_button_cancel_verify, "ביטול")
DEF_STRING(failure_message_unknown, ".הורדת קבצי משחק נכשלה")
DEF_STRING(failure_message_cancelled, ".ההורדה בוטלה")
DEF_STRING(failure_message_connection, ".לא ניתן להתחבר לשרתי GOOGLE PLAY\n.אנא נסה שנית מאוחר יותר")
DEF_STRING(failure_message_license, ".על פי שרתי GOOGLE PLAY, משחק זה לא נקנה מהחנות")
DEF_STRING(failure_message_sdcard, "אחסון מלא, אנא פנה קצת מקום")
DEF_STRING(preparing_game_files, "...מכין קבצי משחק")
DEF_STRING(cancel, "ביטול")
DEF_STRING(exit_confirmation_message, "?זהו הולכים\n.רק זכרו לשמור את המשחק\n!נשמח לראותכם שוב")
DEF_STRING(expansion_downloader_upper_text, "מוריד קבצי משחק")
DEF_STRING(expansion_downloader_upper_text_validating, "אימות קבצי משחק")
DEF_STRING(choose_save_slot, "בחר משחק לשמירה")
// DEF_STRING(empty_slot, "מקום פנוי") - save game names doesn't take non latin chars
DEF_STRING(choose_load_slot, "בחר משחק לטעינה")
DEF_STRING(enter_save_name, ":הכנס שם לשמירה")
DEF_STRING(save_success, "שמירת משחק בוצעה בהצלחה")
DEF_STRING(save_failure, "לא ניתן לשמור את המשחק בזמן זה")
DEF_STRING(load_success, "טעינת משחק בוצעה בהצלחה")
DEF_STRING(load_failure, "לא ניתן לטעון את המשחק בזמן זה")
DEF_STRING(save_game_reminder, ".המשחק מושהה - מומלץ לבצע שמירת משחק מפעם לפעם")
DEF_STRING(files_fraction, "%1$ / %2$ קבצים")
DEF_STRING(save_progress_dialog, "...שומר, אנא המתן")
DEF_STRING(load_progress_dialog, "...טוען, אנא המתן")
DEF_STRING(no_saved_games, "אין שמירות")
DEF_STRING(continue_, "המשך")
DEF_STRING(save_game, "שמירה")
DEF_STRING(load_game, "טעינה")
DEF_STRING(new_game, "משחק חדש")
DEF_STRING(settings, "הגדרות")
DEF_STRING(tutorial, "הדרכה")
DEF_STRING(game_tutorial, "הדרכה")
DEF_STRING(exit_button, "יציאה")
DEF_STRING(controls, "ממשק משתמש")
DEF_STRING(about, "אודות")
DEF_STRING(back, "חזרה")
DEF_STRING(menu_subtitle, "מהדורת שנת ה-25")
DEF_STRING(shader_test_message, "בודק ביצועי גרפיקה (פעם ראשונה בלבד)")
DEF_STRING(rate_message, "!אנחנו מקווים שנהנת לשחק ב%s. בבקשה דרג אותנו")
DEF_STRING(rate, "!כן, דרג עכשיו")
DEF_STRING(rate_later, "הזכר לי מאוחר יותר")
DEF_STRING(rate_cancel, "לא, תודה")
DEF_STRING(tutorial_prompt, "?תרצה לראות את סרטון ההדרכה")
DEF_STRING(graphic_setting_message, "לחווית משחק חלקה, אל תבחר הגדרת גרפיקה גבוהה יותר מברירת המחדל - היא מבוססת על היכולות הגרפיות של מכשירך (GPU).")
DEF_STRING(mt32_warning_message, "אנא שים לב שאפשרות זו לא נתמכת על כל המכשירים. אם אתה חווה  הפרעות במוזיקה או ביצועים נמוכים, אנא נסה להפעיל מחדש את מכשירך ולבחור אפשרות אחרת מרשימה זו.")
DEF_STRING(prepare_game_files_no_space_message, ".אין מספיק מקום על מכשירך. אנא פנה לפחות %s ונסה שוב")
DEF_STRING(storage_unavailable, "התקן האחסון של מכשירך לא זמין - האם הוא מחובר כהתקן USB ?")
DEF_STRING(new_game_confirmation, "?מתחילים מחדש\n.רק זכרו לשמור את המשחק\n!משחק מהנה")
DEF_STRING(rate_us, "דרג אותנו")
DEF_STRING(store_page, "דף החנות")
DEF_STRING(extras, "תוספות")
DEF_STRING(error_opening_epub_file, "אתה צריך להתקין אפליקציה שיכולה לפתוח ספרים (קבצי .epub)")
DEF_STRING(subtitle_speed, "מהירות כתוביות")
DEF_STRING(share_chooser, "...שתף עם")
DEF_STRING(share_message, "תראו איזה משחק מגניב קניתי הרגע - קלאסיקה נצחית!")
DEF_STRING(open_house_prompt, "?אתם מתחילים משחק חדש במצב 'בית פתוח', שיאפשר לכם לשחק מחדש בכל הפאזלים במשחק להנאתכם. להמשיך")
DEF_STRING(skip_english_puzzle_popup, "?הפאזל הבא מבוסס אנגלית, ולא תומך בשפה שלכם באופן מלא. תרצו לדלג עליו")
DEF_STRING(microscope_puzzle_popup, ".טיפ: בחר את כלי המשחק, ואז בחר ביעד כדי להזיז אותו")
DEF_STRING(bishops_puzzle_popup, ".גע ברץ בכדי להזיז אותו. לפעמים ישנם כמה יעדים, ולפעמים הרץ לא יכול לזוז בכלל")
DEF_STRING(achievements, "הישגים")
DEF_STRING(achievement_popup_title, "!זכית בהישג")
DEF_STRING(enable_achievement_popup_checkbox, "הצג רשימת הישגים")
DEF_STRING(facebook_share_achievement_btn, "שתף בפייסבוק")
DEF_STRING(facebook_login_dialog_title, "!התחבר לפייסבוק על מנת לשתף את הישגיך במשחק")
DEF_STRING(facebook_share_achievement_dialog_title, "...שתף את ההישג החדש בקיר שלך")
DEF_STRING(facebook_share_achievement_input_hint, "המסר שלך כאן")
DEF_STRING(facebook_share_achievement_success_toast, "ההישג שותף בהצלחה")
DEF_STRING(facebook_share_achievement_failure_toast, "אירעה תקלה כששיתפת את ההישג")
DEF_STRING(like_view_error, "אירעה תקלה כשלחצת על כפתור הלייק")
DEF_STRING(error_opening_extra_file, ".אנחנו לא מצליחים לפתוח את הקובץ %s. וודא שמותקן אצלך היישום המתאים")
DEF_STRING(load_change_language_popup, "?השמירה הזאת נוצרה עבור שפה אחרת במשחק ולא ניתן להשתמש בה. התרצה לעבור לאותה שפה לפני הטעינה")
DEF_STRING(no_amazon_appstore, "חנות היישומים של אמזון לא מותקנת במכשיר הזה")
DEF_STRING(control_mode_enhanced_desktop, "משופר")
DEF_STRING(control_mode_enhanced_desktop_classic_bar, "משופר עם הפקודות המקוריות")
           
#endif

END_LOCALE

END_STRINGS

#endif /* fotaq_strings_h */
