//
//  ihnm_strings.h
//  scummvm
//
//  Created by Omer Gilad on 10/7/15.
//
//

#ifndef ihnm_strings_h
#define ihnm_strings_h


BEGIN_STRINGS


BEGIN_LOCALE(ENGLISH)


//
// Non-localized
//
DEF_STRING(english, "English")
DEF_STRING(english_sub, "English Subtitles")
DEF_STRING(german, "Deutsch")
DEF_STRING(german_sub, "Deutsch Untertitel")
DEF_STRING(spanish, "Español")
DEF_STRING(spanish_sub, "Subtítulos en Español")
DEF_STRING(portuguese, "Português")
DEF_STRING(portuguese_sub, "Legendas em Português")
DEF_STRING(french, "Français")
DEF_STRING(french_sub, "Sous-titres Français")
DEF_STRING(russian, "Pу́сский")
DEF_STRING(russian_sub, "Pусские Cубтитры")
DEF_STRING(italian, "Italiano")
DEF_STRING(italian_sub, "Sottotitoli Italiano")
DEF_STRING(czech, "Čeština")
DEF_STRING(czech_sub, "Ceské Titulky")
DEF_STRING(polish, "Polski")
DEF_STRING(polish_sub, "Polskie Napisy")
DEF_STRING(swedish, "Svenska")
DEF_STRING(swedish_sub, "Svenska undertexter")
DEF_STRING(hebrew, "עברית")
DEF_STRING(hebrew_sub, "כתוביות בעברית")

DEF_STRING(sfx_volume, "SFX")


DEF_STRING(quit, "EXIT")
DEF_STRING(no_sdcard, "Cannot access your external storage.")
DEF_STRING(restart_needed, "Your changes will apply after \'New Game\' OR \'Load\'.")
DEF_STRING(music_mode_no_music, "None")
DEF_STRING(music_mode_original, "AdLib")
DEF_STRING(music_mode_original_recording, "Original")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "General MIDI (EAS)")
DEF_STRING(music_mode_enhanced, "New Recording")
DEF_STRING(voice_mode_voice_subtitles, "Voice And Subtitles")
DEF_STRING(voice_mode_voice_only, "Voice Only")
DEF_STRING(voice_mode_subtitles_only, "Subtitles Only")
DEF_STRING(subtitle_speed, "Subtitle Speed")
DEF_STRING(scaling_option_lq_shader, "Medium")
DEF_STRING(scaling_option_shader, "High")
DEF_STRING(scaling_option_shader_native_res, "Ultra")
DEF_STRING(scaling_option_software, "Low")
DEF_STRING(scaling_option_none, "Original")
DEF_STRING(control_mode_touch, "Touch")
DEF_STRING(control_mode_touch_desc, "HOTSPOTS BASED CONTROLS")
DEF_STRING(control_mode_classic, "Classic")
DEF_STRING(control_mode_classic_desc, "DISPLAY CURSOR AND USE THE ACTIONS BUTTONS")
DEF_STRING(control_mode_touch_classic_bar, "TOUCH WITH ORIGINAL ACTIONS")
DEF_STRING(music_mode, "MUSIC")
DEF_STRING(voice_mode, "VOICE")
DEF_STRING(music_volume, "MUSIC")
DEF_STRING(speech_volume, "VOICE")
DEF_STRING(language, "LANGUAGE")
DEF_STRING(scaling_option, "GRAPHICS")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "Unable to create game files. Is your external storage accessible?")
DEF_STRING(unable_to_create_game_files_error_dialog, "The local game files are corrupt. Would you like to download the game files again?")
DEF_STRING(ok, "OK")
DEF_STRING(yes, "YES")
DEF_STRING(no, "NO")
DEF_STRING(text_validation_failed, "Expansion file validation failed. The file is corrupted and needs to be downloaded again.")
DEF_STRING(text_button_pause, "Pause")
DEF_STRING(text_button_resume, "Resume")
DEF_STRING(text_button_cancel, "CANCEL")
DEF_STRING(text_button_cancel_verify, "CANCEL")
DEF_STRING(failure_message_unknown, "Failed to start downloading game files.")
DEF_STRING(failure_message_cancelled, "The download was cancelled.")
DEF_STRING(failure_message_connection, "Could not connect to Google Play\'s servers.\nPlease try again later.")
DEF_STRING(failure_message_license, "According ot Google Play, this game client is unlicensed.")
DEF_STRING(failure_message_sdcard, "Storage is full, free up some space.")
DEF_STRING(preparing_game_files, "Preparing game files...")
DEF_STRING(cancel, "CANCEL")
DEF_STRING(exit_confirmation_message, "Exit the game now?\nUnsaved progress will be lost.")
DEF_STRING(expansion_downloader_upper_text, "Downloading game files")
DEF_STRING(expansion_downloader_upper_text_validating, "Validating game files")
DEF_STRING(choose_save_slot, "SAVE")
DEF_STRING(choose_load_slot, "LOAD")
DEF_STRING(enter_save_name, "Enter save name:")
DEF_STRING(save_success, "Game saved successfully")
DEF_STRING(save_failure, "Cannot save the game at this time")
DEF_STRING(load_success, "Loaded game successfully")
DEF_STRING(load_failure, "Cannot load at this time")
DEF_STRING(load_failure_no_saves, "No save games are available. Please save the game first.")
DEF_STRING(save_game_reminder, "%s is paused - it is recommended that you save your game from time to time.")
DEF_STRING(files_fraction, "%1$s / %2$s files")
DEF_STRING(save_progress_dialog, "Saving, please wait...")
DEF_STRING(load_progress_dialog, "Loading, please wait...")
DEF_STRING(no_saved_games, "There are no saved games")
DEF_STRING(continue_, "CONTINUE")
DEF_STRING(save_game, "SAVE")
DEF_STRING(load_game, "LOAD")
DEF_STRING(new_game, "NEW GAME")
DEF_STRING(settings, "SETTINGS")
DEF_STRING(tutorial, "TUTORIAL")
DEF_STRING(game_tutorial, "Game Tutorial")
DEF_STRING(exit_button, "QUIT")
DEF_STRING(controls, "CONTROLS")
DEF_STRING(about, "ABOUT")
DEF_STRING(back, "BACK")
DEF_STRING(menu_subtitle, "25TH ANNIVERSARY EDITION")
DEF_STRING(shader_test_message, "Testing graphics performance (first time only)")
DEF_STRING(rate_message, "We hope that you enjoy playing %s. Please rate it!")
DEF_STRING(rate, "Yes, rate now!")
DEF_STRING(rate_later, "Remind me later")
DEF_STRING(rate_cancel, "No, thanks")
DEF_STRING(tutorial_prompt, "Would you like to watch the tutorial video?")
DEF_STRING(graphic_setting_message, "For smooth gameplay, do not increase the default graphic settings - they are based on your device\'s graphic performance (GPU).")
DEF_STRING(mt32_warning_message, "Please note that this feature is not supported on all devices. If you experience \"cracking\" in the music or low performance, please try to reboot your device and to choose another option from this list.")
DEF_STRING(prepare_game_files_no_space_message, "There is no free space on your device.\nPlease free up %s and then start again.")
DEF_STRING(storage_unavailable, "Your device\'s storage is unavailable - is it connected as a USB drive?")
DEF_STRING(new_game_confirmation, "Are you sure you want to start a new game?\nYour unsaved progress will be lost.")
DEF_STRING(rate_us, "RATE US")
DEF_STRING(store_page, "Store Page")
DEF_STRING(share_chooser, "Share with...")
DEF_STRING(share_message, "Check out this cool new game I just bought - a timeless classic!")
DEF_STRING(open_house_prompt, "This will start a new game in \'Open House\' mode, which allows you to replay all the puzzles in the game for your leisure. Continue?")
DEF_STRING(achievement_popup_title, "You got an achievement! ")
DEF_STRING(enable_achievement_popup_checkbox, "Show achievement popups")
DEF_STRING(facebook_share_achievement_btn, "Share with Facebook")
DEF_STRING(facebook_login_dialog_title, "Log into Facebook in order to share your game achievements!")
DEF_STRING(facebook_share_achievement_dialog_title, "Share the new achievement on your wall...")
DEF_STRING(facebook_share_achievement_input_hint, "Your message here")
DEF_STRING(facebook_share_achievement_success_toast, "The achievement was shared successfully")
DEF_STRING(facebook_share_achievement_failure_toast, "There was an error while sharing the achievement")
DEF_STRING(skip_english_puzzle_popup, "The following puzzle is English-based, and does not fully support your language.\nWould you like to skip it?")
DEF_STRING(microscope_puzzle_popup, "TIP: select the game piece, and then select the destination to make it move.")
DEF_STRING(like_view_error, "There was an error while using the Like button")
DEF_STRING(error_opening_extra_file, "Could not open the file %s. Make sure you have an appropriate app installed.")
DEF_STRING(error_opening_epub_file, "You need to install an app that can open Books (.epub files)")
DEF_STRING(achievements, "Achievements")
DEF_STRING(extras, "Extras")
DEF_STRING(bishops_puzzle_popup, "Touch a bishop in order to move it. Sometimes there are multiple destinations, and sometimes a bishop cannot move at all.")
DEF_STRING(load_change_language_popup, "This save was created with a different language of the game and can\'t be used.\nWould you like to switch to that language before loading?")
DEF_STRING(no_amazon_appstore, "The Amazon Appstore is not installed on this device")

// TODO: localize
DEF_STRING(control_mode_enhanced_desktop, "Enhanced")
DEF_STRING(control_mode_enhanced_desktop_classic_bar, "Enhanced with original actions")


END_LOCALE



BEGIN_LOCALE(GERMAN)

DEF_STRING(quit, "BEENDEN")
DEF_STRING(no_sdcard, "KANN AUF EXTERNEN SPEICHER NICHT ZUGREIFEN.")
DEF_STRING(restart_needed, "ÄNDERUNGEN WERDEN WIRKSAM NACH DEM START EINES NEUEN SPIELS ODER DURCH LADEN EINES SPIELSTANDS.")
DEF_STRING(music_mode_no_music, "KEINER")
DEF_STRING(music_mode_original, "AdLib")
DEF_STRING(music_mode_original_recording, "Original")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "General MIDI (EAS)")
DEF_STRING(music_mode_enhanced, "NEUE AUFNAHME")
DEF_STRING(voice_mode_voice_subtitles, "SPRACHAUSGABE UND UNTERTITEL")
DEF_STRING(voice_mode_voice_only, "NUR SPRACHAUSGABE")
DEF_STRING(voice_mode_subtitles_only, "NUR UNTERTITEL")
DEF_STRING(subtitle_speed, "Untertitel-Geschwindigkeit")
DEF_STRING(scaling_option_lq_shader, "MITTEL")
DEF_STRING(scaling_option_shader, "HOCH")
DEF_STRING(scaling_option_shader_native_res, "ULTRA")
DEF_STRING(scaling_option_software, "NIEDRIG")
DEF_STRING(scaling_option_none, "ORIGINAL")
DEF_STRING(control_mode_touch, "BERÜHRUNG")
DEF_STRING(control_mode_touch_desc, "AUF BRENNPUNKTEN BASIERENDE STEUERUNG")
DEF_STRING(control_mode_touch_classic_bar, "BEDIENOBERFLÄCHE MIT ORIGINAL-SYMBOLEN")
DEF_STRING(control_mode_classic, "KLASSISCH")
DEF_STRING(control_mode_classic_desc, "CURSOR ANZEIGEN UND AKTIONSTASTEN NUTZEN")
DEF_STRING(music_mode, "MUSIK")
DEF_STRING(voice_mode, "SPRACHAUSGABE")
DEF_STRING(music_volume, "MUSIK")
DEF_STRING(speech_volume, "SPRACHAUSGABE")
DEF_STRING(language, "SPRACHE")
DEF_STRING(scaling_option, "GRAFIK")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "Kann Spieldateien nicht erstellen. Ist externer Speicherplatz verfügbar?")
DEF_STRING(unable_to_create_game_files_error_dialog, "Die lokalen Spieldateien sind beschädigt. Sollen die Spieldateien erneut heruntergeladen werden?")
DEF_STRING(ok, "OK")
DEF_STRING(yes, "JA")
DEF_STRING(no, "NEIN")
DEF_STRING(text_validation_failed, "Gültigkeitsprüfung der Erweiterungsdatei gescheitert. Die Datei ist beschädigt und muss erneut heruntergeladen werden.")
DEF_STRING(text_button_pause, "PAUSE")
DEF_STRING(text_button_resume, "FORTSETZEN")
DEF_STRING(text_button_cancel, "ABBRECHEN")
DEF_STRING(text_button_cancel_verify, "ABBRECHEN")
DEF_STRING(failure_message_unknown, "HERUNTERLADEN DER SPIELDATEIEN KONNTE NICHT GESTARTET WERDEN.")
DEF_STRING(failure_message_cancelled, "DER DOWNLOAD WURDE ABGEBROCHEN.")
DEF_STRING(failure_message_connection, "KONNTE NICHT MIT DEN SERVERN VON GOOGLE PLAY VERBINDEN. BITTE SPÄTER ERNEUT VERSUCHEN.")
DEF_STRING(failure_message_license, "GEMÄSS GOOGLE PLAY IST DIESE KOPIE DES SPIELES NICHT LIZENSIERT.")
DEF_STRING(failure_message_sdcard, "SPEICHER IST VOLL, BITTE SPEICHERPLATZ SCHAFFEN.")
DEF_STRING(preparing_game_files, "SPIELDATEIEN WERDEN VORBEREITET...")
DEF_STRING(cancel, "ABBRECHEN")
DEF_STRING(exit_confirmation_message, "Beenden Sie das Spiel jetzt? NICHT GESPEICHERTER FORTSCHRITT GEHT VERLOREN.")
DEF_STRING(expansion_downloader_upper_text, "SPIELDATEIEN WERDEN HERUNTERGELADEN")
DEF_STRING(expansion_downloader_upper_text_validating, "SPIELEDATEIEN WERDEN AUF GÜLTIGKEIT GEPRÜFT")
DEF_STRING(choose_save_slot, "SPEICHERN")
DEF_STRING(choose_load_slot, "LADEN")
DEF_STRING(enter_save_name, "NAMEN FÜR DEN SPIELSTAND EINGEBEN:")
DEF_STRING(save_success, "Spiel erfolgreich gespeichert.")
DEF_STRING(save_failure, "Kann Spiel zurzeit nicht speichern.")
DEF_STRING(load_success, "Spiel erfolgreich geladen.")
DEF_STRING(load_failure, "Kann Spiel zurzeit nicht laden.")
DEF_STRING(save_game_reminder, "%s ist pausiert – es wird empfohlen, dass Spiel von Zeit zu Zeit zu speichern.")
DEF_STRING(files_fraction, "%1$s / %2$s Dateien")
DEF_STRING(save_progress_dialog, "SPEICHERT GERADE, BITTE WARTEN ...")
DEF_STRING(load_progress_dialog, "LÄDT GERADE, BITTE WARTEN ...")
DEF_STRING(no_saved_games, "Es gibt keine gespeicherten Spielstände.")
DEF_STRING(continue_, "FORTFAHREN")
DEF_STRING(save_game, "SPEICHERN")
DEF_STRING(load_game, "LADEN")
DEF_STRING(new_game, "NEUES SPIEL")
DEF_STRING(settings, "EINSTELLUNGEN")
DEF_STRING(tutorial, "ANLEITUNG")
DEF_STRING(game_tutorial, "Spiel Tutorial")
DEF_STRING(exit_button, "BEENDEN")
DEF_STRING(controls, "SPIELSTEUERUNG")
DEF_STRING(about, "ÜBER")
DEF_STRING(back, "ZURÜCK")
DEF_STRING(menu_subtitle, "25TH ANNIVERSARY EDITION")
DEF_STRING(shader_test_message, "Grafik-Leistung wird getestet (nur beim ersten Mal)")
DEF_STRING(rate_message, "Wir hoffen, dass Sie viel Freude dabei haben, %s zu spielen. Bitte bewerten Sie das Spiel!")
DEF_STRING(rate, "JA, JETZT BEWERTEN")
DEF_STRING(rate_later, "SPÄTER DARAN ERINNERN")
DEF_STRING(rate_cancel, "NEIN, DANKE")
DEF_STRING(tutorial_prompt, "MÖCHTEST DU DIE VIDEO-ANLEITUNG SEHEN ?")
DEF_STRING(graphic_setting_message, "Um ruckelfrei spielen zu können, erhöhe nicht die standardmäßigen Grafikeinstellungen - sie basieren auf der Grafikleistung (GPU) des Geräts.")
DEF_STRING(mt32_warning_message, "Bitte beachte, dass diese Funktion nicht auf allen Geräten unterstützt wird. Wenn die Musik „stottert“ oder zu langsam abgespielt wird, fahre bitte das Gerät neu hoch und wähle eine andere Option aus dieser Liste aus.")
DEF_STRING(prepare_game_files_no_space_message, "AUF DEM GERÄT IST KEIN FREIER SPEICHER VERFÜGBAR. BITTE MACHE %s FREI UND STARTE DANN ERNEUT.")
DEF_STRING(storage_unavailable, "DER GERÄTESPEICHER IST NICHT VERFÜBAR - IST ER ALS USB-GERÄT ANGESCHLOSSEN?")
DEF_STRING(new_game_confirmation, "MÖCHTEST DU WIRKLICH EIN NEUES SPIEL STARTEN? DEIN NICHT GESPEICHERTER SPIELSTAND GEHT VERLOREN.")
DEF_STRING(rate_us, "Bewerten Sie uns")
DEF_STRING(store_page, "Seite speichern")
DEF_STRING(share_chooser, "Share with...")
DEF_STRING(share_message, "Check out this cool new game I just bought - a timeless classic!")
DEF_STRING(open_house_prompt, "This will start a new game in \'Open House\' mode, which allows you to replay all the puzzles in the game for your leisure. Continue?")
DEF_STRING(achievement_popup_title, "You got an achievement! ")
DEF_STRING(enable_achievement_popup_checkbox, "Show achievement popups")
DEF_STRING(facebook_share_achievement_btn, "Share with Facebook")
DEF_STRING(facebook_login_dialog_title, "Log into Facebook in order to share your game achievements!")
DEF_STRING(facebook_share_achievement_dialog_title, "Share the new achievement on your wall...")
DEF_STRING(facebook_share_achievement_input_hint, "Your message here")
DEF_STRING(facebook_share_achievement_success_toast, "The achievement was shared successfully")
DEF_STRING(facebook_share_achievement_failure_toast, "There was an error while sharing the achievement")
DEF_STRING(skip_english_puzzle_popup, "The following puzzle is English-based, and does not fully support your language.\nWould you like to skip it?")
DEF_STRING(microscope_puzzle_popup, "TIP: select the game piece, and then select the destination to make it move.")
DEF_STRING(like_view_error, "There was an error while using the Like button")
DEF_STRING(error_opening_extra_file, "Could not open the file %s. Make sure you have an appropriate app installed.")
DEF_STRING(error_opening_epub_file, "You need to install an app that can open Books (.epub files)")
DEF_STRING(achievements, "Achievements")
DEF_STRING(extras, "Extras")
DEF_STRING(bishops_puzzle_popup, "Touch a bishop in order to move it. Sometimes there are multiple destinations, and sometimes a bishop cannot move at all.")
DEF_STRING(load_change_language_popup, "Der Spielstand wurde in einer anderen Sprache des Spiels gespeichert und kann nicht verwendet werden.\nVor dem Laden zu dieser Sprache wechseln?")
DEF_STRING(no_amazon_appstore, "The Amazon Appstore is not installed on this device")


END_LOCALE



BEGIN_LOCALE(FRENCH)

DEF_STRING(quit, "QUITTER")
DEF_STRING(no_sdcard, "Impossible d\'acceder a un stockage externe.")
DEF_STRING(restart_needed, "Vos changements seront appliques apres \'Nouvelle Partie\' ou \'Charger\'.")
DEF_STRING(music_mode_no_music, "Aucune")
DEF_STRING(music_mode_original, "AdLib")
DEF_STRING(music_mode_original_recording, "Originelle")
DEF_STRING(music_mode_original_mt32, "MT-32")
DEF_STRING(music_mode_original_eas, "General MIDI (EAS)")
DEF_STRING(music_mode_enhanced, "Nouvel Enregistrement")
DEF_STRING(voice_mode_voice_subtitles, "Voix et sous-titres")
DEF_STRING(voice_mode_voice_only, "Voix uniquement")
DEF_STRING(voice_mode_subtitles_only, "Sous-titres uniquement")
DEF_STRING(subtitle_speed, "Vitesse des sous-titres")
DEF_STRING(scaling_option_lq_shader, "Moyen")
DEF_STRING(scaling_option_shader, "Eleve")
DEF_STRING(scaling_option_shader_native_res, "Ultra")
DEF_STRING(scaling_option_software, "Bas")
DEF_STRING(scaling_option_none, "Originel")
DEF_STRING(control_mode_touch, "Tactile")
DEF_STRING(control_mode_touch_desc, "COMMANDES BASEES SUR LES ENDROITS CLES")
DEF_STRING(control_mode_touch_classic_bar, "TACTILE AVEC ACTIONS D\'ORIGINES")
DEF_STRING(control_mode_classic, "Classic")
DEF_STRING(control_mode_classic_desc, "AFFICHEZ LE CURSEUR ET UTILISEZ LES TOUCHES D\'ACTION")
DEF_STRING(music_mode, "Musique")
DEF_STRING(voice_mode, "Voix")
DEF_STRING(music_volume, "Musique")
DEF_STRING(speech_volume, "Voix")
DEF_STRING(language, "Langage")
DEF_STRING(scaling_option, "Graphiques")
DEF_STRING(unable_to_create_game_files_connect_external_storage, "Impossible de creer les fichiers du jeu. Un stockage externe est-il disponible ?")
DEF_STRING(unable_to_create_game_files_error_dialog, "Les fichiers du jeu sont corrompus. Voulez-vous les telecharger de nouveau ?")
DEF_STRING(ok, "OK")
DEF_STRING(yes, "OUI")
DEF_STRING(no, "NON")
DEF_STRING(text_validation_failed, "La validation du fichier d\'extension a echouee. Le fichier est corrompu et doit etre telecharge de nouveau.")
DEF_STRING(text_button_pause, "Pause")
DEF_STRING(text_button_resume, "Reprendre")
DEF_STRING(text_button_cancel, "ANNULER")
DEF_STRING(text_button_cancel_verify, "ANNULER")
DEF_STRING(failure_message_unknown, "Le telechargement des fichiers du jeu a echoue.")
DEF_STRING(failure_message_cancelled, "Le telechargement a ete annule.")
DEF_STRING(failure_message_connection, "Impossible de se connecter aux serveur de Google Play.\nEssayez de nouveau plus tard.")
DEF_STRING(failure_message_license, "Selon Google Play, ce client de jeu est sans licence.")
DEF_STRING(failure_message_sdcard, "Le disque de stockage est plein, liberez de l\'espace.")
DEF_STRING(preparing_game_files, "Preparation des fichiers du jeu…")
DEF_STRING(cancel, "ANNULER")
DEF_STRING(exit_confirmation_message, "Quittez le jeu maintenant ?\nLes progres non sauvegardes seront perdus.")
DEF_STRING(expansion_downloader_upper_text, "Telechargement des fichiers du jeu")
DEF_STRING(expansion_downloader_upper_text_validating, "Validation des fichiers du jeu")
DEF_STRING(choose_save_slot, "Sauvegarder")
DEF_STRING(choose_load_slot, "Charger")
DEF_STRING(enter_save_name, "Nom de la sauvegarde:")
DEF_STRING(save_success, "Succes de la sauvegarde")
DEF_STRING(save_failure, "Impossible de sauver la partie pour l\'instant")
DEF_STRING(load_success, "Succes du chargement")
DEF_STRING(load_failure, "Impossible de charger la partie pour l\'instant")
DEF_STRING(save_game_reminder, "Partie est en pause - il est recommande de sauvegarder la partie de temps en temps.")
DEF_STRING(files_fraction, "%1$s / %2$s fichiers")
DEF_STRING(save_progress_dialog, "Sauvegarde en cours…")
DEF_STRING(load_progress_dialog, "Chargement en cours…")
DEF_STRING(no_saved_games, "Il n\'y a pas de partie sauvegardee")
DEF_STRING(continue_, "Continuer")
DEF_STRING(save_game, "Sauvegarder")
DEF_STRING(load_game, "Charger")
DEF_STRING(new_game, "Nouvelle Partie")
DEF_STRING(settings, "Options")
DEF_STRING(tutorial, "Tutoriel")
DEF_STRING(game_tutorial, "Tutoriel du jeu")
DEF_STRING(exit_button, "ADIEU")
DEF_STRING(controls, "Commandes")
DEF_STRING(about, "a propos")
DEF_STRING(back, "Retour")
DEF_STRING(menu_subtitle, "EDITION DU 20IEME ANNIVERSAIRE")
DEF_STRING(shader_test_message, "Test des performances graphiques (premier lancement uniquement)")
DEF_STRING(rate_message, "Nous espérons que vous aimez jouer a %s. Noter le s\'il vous plait !")
DEF_STRING(rate, "Oui, mettre une note maintenant !")
DEF_STRING(rate_later, "Me le rappeler plus tard")
DEF_STRING(rate_cancel, "Non, merci")
DEF_STRING(tutorial_prompt, "Voulez-vous regarder le tutoriel video ?")
DEF_STRING(graphic_setting_message, "Pour un jeu sans saccades, gardez les parametres graphiques par defaut – ils prennent en compte les performances graphiques (GPU) de votre appareil.")
DEF_STRING(mt32_warning_message, "Veuillez notez que cette fonctionalite n\'est supportee sur tous les appareils. Si vous rencontrez des \"craquement\" dans la musique ou des faibles performances, essayez de redemarrer votre appareil et de choisir une option differente dans cette liste.")
DEF_STRING(prepare_game_files_no_space_message, "Il n\'y a pas d\'espace disponible sur votre appareil.\nVeuillez liberer %s puis reessayer.")
DEF_STRING(storage_unavailable, "Le peripherique de stockage de votre appareil n\'est pas disponible – est-il connecte comme disque USB ?")
DEF_STRING(new_game_confirmation, "Etes vous sur de vouloir commencer une nouvelle partie ?\nVos progres non sauvegardes seront perdus.")
DEF_STRING(rate_us, "Nous Evaluer")
DEF_STRING(store_page, "Store Page")
DEF_STRING(share_chooser, "Partager…")
DEF_STRING(share_message, "Decouvrez ce nouveau jeu cool que je viens d\'acheter – un classique qui ne vieillit pas !")
DEF_STRING(open_house_prompt, "Cela commencera une nouvelle partie en mode \'Maison Ouverte\', qui permet de rejouer tous les puzzles du jeu a votre guise. Continuer ?")
DEF_STRING(achievement_popup_title, "Vous avez un Succes ! ")
DEF_STRING(enable_achievement_popup_checkbox, "Afficher les Succes")
DEF_STRING(facebook_share_achievement_btn, "Partager sur Facebook")
DEF_STRING(facebook_login_dialog_title, "Connectez-vous a Facebook pour partager vos Succes !")
DEF_STRING(facebook_share_achievement_dialog_title, "Postez les nouveaux Succes sur votre mur…")
DEF_STRING(facebook_share_achievement_input_hint, "Votre message ici")
DEF_STRING(facebook_share_achievement_success_toast, "Le Succes a ete partage avec succes")
DEF_STRING(facebook_share_achievement_failure_toast, "Une erreur est intervenue lors du partage de votre Succes")
DEF_STRING(skip_english_puzzle_popup, "Le puzzle suivant est base sur l'anglais, et ne supporte pas totalement votre langue.\nVoulez-vous le sauter ?")
DEF_STRING(microscope_puzzle_popup, "Astuce : Selectionez une piece du jeu, et ensuite selectionez une destination pour la deplacer.")
DEF_STRING(like_view_error, "Une erreur est survenue lors de l\'utilisation du bouton \'J\'aime\'.")
DEF_STRING(error_opening_extra_file, "Erreur lors de l\'ouverture du fichier %s. Vérifier que vous avez installe une application appropriee pour le lire.")
DEF_STRING(error_opening_epub_file, "Vous avez besoin d\'installer une application qui peut ouvrir les livres electroniques (fichiers .epub).")
DEF_STRING(achievements, "Succes")
DEF_STRING(extras, "Supplements")
DEF_STRING(bishops_puzzle_popup, "Selectionnez le fou pour le deplacer. Parfois plusieurs directions sont possibles, parfois aucune.")
DEF_STRING(load_change_language_popup, "Cette sauvegarde a ete creee dans une langue du jeu differente et ne peut pas etre utilisee.\nVoulez-vous selectionner cette langue avant le chargement ?")
DEF_STRING(no_amazon_appstore, "The Amazon Appstore is not installed on this device")


END_LOCALE



END_STRINGS

#endif /* ihnm_strings_h */
